// 120 frases A1/A2/B1 (inglés americano más usado)
// "alts": traducciones alternativas válidas que también se aceptan
export const PHRASES = [
  // ============ A1 ============
  { level:"A1", es:"Hola, ¿cómo estás?", en:"Hi, how are you?", alts:["Hello, how are you?","Hey, how are you?"], hint:"Saludo casual con pregunta" },
  { level:"A1", es:"Me llamo Juan", en:"My name is Juan", alts:["I´m Juan","I am Juan"], hint:"Presentarse" },
  { level:"A1", es:"Soy de México", en:"I´m from Mexico", alts:["I am from Mexico"], hint:"Origen → from" },
  { level:"A1", es:"Mucho gusto", en:"Nice to meet you", alts:["Pleased to meet you","Good to meet you"], hint:"Conocer a alguien por primera vez" },
  { level:"A1", es:"¿Cómo te llamas?", en:"What´s your name?", alts:["What is your name?"], hint:"Preguntar el nombre" },
  { level:"A1", es:"¿De dónde eres?", en:"Where are you from?", alts:["Where do you come from?"], hint:"Origen → where + from" },
  { level:"A1", es:"¿Cuántos años tienes?", en:"How old are you?", alts:[], hint:"En inglés se 'es' la edad, no se 'tiene'" },
  { level:"A1", es:"Tengo 25 años", en:"I´m 25 years old", alts:["I am 25","I´m 25"], hint:"Usa to be, no to have" },
  { level:"A1", es:"No entiendo", en:"I don´t understand", alts:["I do not understand"], hint:"Negación con don´t" },
  { level:"A1", es:"¿Puedes ayudarme?", en:"Can you help me?", alts:["Could you help me?"], hint:"Pedir ayuda con can/could" },
  { level:"A1", es:"¿Qué hora es?", en:"What time is it?", alts:["What´s the time?","Do you know what time it is?"], hint:"Inversión: time + is + it" },
  { level:"A1", es:"Buenos días", en:"Good morning", alts:[], hint:"Solo en la mañana" },
  { level:"A1", es:"Buenas noches", en:"Good night", alts:[], hint:"Para despedirse de noche" },
  { level:"A1", es:"Muchas gracias", en:"Thank you very much", alts:["Thanks a lot","Thank you so much"], hint:"" },
  { level:"A1", es:"De nada", en:"you´re welcome", alts:["No problem","don´t mention it"], hint:"" },
  { level:"A1", es:"Lo siento", en:"I´m sorry", alts:["I am sorry","Sorry"], hint:"" },
  { level:"A1", es:"Disculpa", en:"Excuse me", alts:[], hint:"Para llamar la atención" },
  { level:"A1", es:"Te amo", en:"I love you", alts:[], hint:"" },
  { level:"A1", es:"Tengo hambre", en:"I´m hungry", alts:["I am hungry"], hint:"En inglés se 'es' hambriento" },
  { level:"A1", es:"Tengo sed", en:"I´m thirsty", alts:["I am thirsty"], hint:"to be + thirsty" },
  { level:"A1", es:"Estoy cansado", en:"I´m tired", alts:["I am tired"], hint:"" },
  { level:"A1", es:"Tengo frío", en:"I´m cold", alts:["I am cold"], hint:"to be + cold" },
  { level:"A1", es:"Tengo calor", en:"I´m hot", alts:["I am hot"], hint:"to be + hot" },
  { level:"A1", es:"Tengo un hermano", en:"I have a brother", alts:["I´ve got a brother"], hint:"" },
  { level:"A1", es:"Este es mi amigo", en:"This is my friend", alts:[], hint:"" },
  { level:"A1", es:"Me gusta el café", en:"I like coffee", alts:[], hint:"like sin 'the'" },
  { level:"A1", es:"No me gusta el pescado", en:"I don´t like fish", alts:["I do not like fish"], hint:"" },
  { level:"A1", es:"¿Dónde está el baño?", en:"Where is the bathroom?", alts:["Where's the bathroom?","Where's the restroom?"], hint:"" },
  { level:"A1", es:"¿Cuánto cuesta?", en:"How much is it?", alts:["How much does it cost?"], hint:"" },
  { level:"A1", es:"Quiero agua, por favor", en:"I want water, please", alts:["I´d like water, please"], hint:"" },
  { level:"A1", es:"Soy estudiante", en:"I´m a student", alts:["I am a student"], hint:"Recuerda el 'a'" },
  { level:"A1", es:"Trabajo en una oficina", en:"I work in an office", alts:["I work at an office"], hint:"in/at + office" },
  { level:"A1", es:"Tengo dos gatos", en:"I have two cats", alts:["I´ve got two cats"], hint:"" },
  { level:"A1", es:"Está lloviendo", en:"It´s raining", alts:["It is raining"], hint:"It como sujeto del clima" },
  { level:"A1", es:"Hace sol hoy", en:"It´s sunny today", alts:["It is sunny today"], hint:"It + is + adjetivo de clima" },
  { level:"A1", es:"Vivo en Nueva York", en:"I live in New York", alts:[], hint:"" },
  { level:"A1", es:"Nos vemos mañana", en:"See you tomorrow", alts:[], hint:"" },
  { level:"A1", es:"Hasta luego", en:"See you later", alts:["See ya"], hint:"" },
  { level:"A1", es:"Que tengas un buen día", en:"Have a nice day", alts:["Have a good day"], hint:"" },
  { level:"A1", es:"No sé", en:"I don´t know", alts:["I do not know"], hint:"" },

  // ============ A2 ============
  { level:"A2", es:"Voy a la tienda", en:"I´m going to the store", alts:["I am going to the store","I´m going to the shop"], hint:"Presente continuo para acción ahora" },
  { level:"A2", es:"Tengo que trabajar mañana", en:"I have to work tomorrow", alts:["I´ve got to work tomorrow"], hint:"have to = obligación" },
  { level:"A2", es:"¿Me trae la cuenta, por favor?", en:"Can I have the check, please?", alts:["Could I have the check, please?","The check, please"], hint:"En USA se dice 'check', no 'bill'" },
  { level:"A2", es:"Estoy buscando la estación de tren", en:"I´m looking for the train station", alts:["I am looking for the train station"], hint:"look for = buscar" },
  { level:"A2", es:"¿Qué significa esta palabra?", en:"What does this word mean?", alts:["What´s the meaning of this word?"], hint:"Auxiliar 'does' antes del sujeto" },
  { level:"A2", es:"¿Cómo se dice esto en inglés?", en:"How do you say this in English?", alts:[], hint:"Pregunta con 'do you' (impersonal)" },
  { level:"A2", es:"Llevo dos días aquí", en:"I´ve been here for two days", alts:["I have been here for two days"], hint:"Present perfect + for" },
  { level:"A2", es:"Me gustaría un café, por favor", en:"I´d like a coffee, please", alts:["I would like a coffee, please"], hint:"Más educado que 'I want'" },
  { level:"A2", es:"¿Podrías repetir, por favor?", en:"Could you repeat that, please?", alts:["Can you repeat that, please?"], hint:"Could = más educado" },
  { level:"A2", es:"Olvidé mis llaves", en:"I forgot my keys", alts:["I´ve forgotten my keys"], hint:"Pasado simple de forget" },
  { level:"A2", es:"Perdí mi teléfono", en:"I lost my phone", alts:["I´ve lost my phone"], hint:"Pasado simple de lose" },
  { level:"A2", es:"Es mi turno", en:"It´s my turn", alts:["It is my turn"], hint:"" },
  { level:"A2", es:"No te preocupes", en:"don´t worry about it", alts:["don´t worry"], hint:"Imperativo negativo" },
  { level:"A2", es:"Solo estoy bromeando", en:"I´m just kidding", alts:["I´m only kidding","I´m just joking"], hint:"" },
  { level:"A2", es:"Eso suena genial", en:"That sounds great", alts:["That sounds awesome","That sounds amazing"], hint:"sound + adjetivo" },
  { level:"A2", es:"Lo pensaré", en:"I'll think about it", alts:["I will think about it"], hint:"think + about" },
  { level:"A2", es:"Depende de ti", en:"It depends on you", alts:["It´s up to you"], hint:"depend ON, no 'of'" },
  { level:"A2", es:"Estoy de acuerdo contigo", en:"I agree with you", alts:[], hint:"agree WITH" },
  { level:"A2", es:"No estoy de acuerdo", en:"I disagree", alts:["I don´t agree"], hint:"" },
  { level:"A2", es:"No importa", en:"It doesn´t matter", alts:["It does not matter"], hint:"" },
  { level:"A2", es:"Quizás después", en:"Maybe later", alts:["Perhaps later"], hint:"" },
  { level:"A2", es:"¿Qué estás haciendo?", en:"What are you doing?", alts:[], hint:"Presente continuo en pregunta" },
  { level:"A2", es:"Estoy viendo la tele", en:"I´m watching TV", alts:["I am watching TV"], hint:"watch para tele/películas" },
  { level:"A2", es:"Fui a la playa ayer", en:"I went to the beach yesterday", alts:[], hint:"Pasado simple de go" },
  { level:"A2", es:"Te llamaré después", en:"I'll call you back", alts:["I will call you back"], hint:"call back = devolver llamada" },
  { level:"A2", es:"¿Estás listo?", en:"Are you ready?", alts:[], hint:"" },
  { level:"A2", es:"¡Apúrate!", en:"Hurry up!", alts:[], hint:"" },
  { level:"A2", es:"Tómate tu tiempo", en:"Take your time", alts:[], hint:"Expresión idiomática" },
  { level:"A2", es:"Tú decides", en:"It´s up to you", alts:["It is up to you"], hint:"" },
  { level:"A2", es:"Déjame pensar", en:"Let me think", alts:[], hint:"let + me + verbo base" },
  { level:"A2", es:"Cambié de opinión", en:"I changed my mind", alts:["I´ve changed my mind"], hint:"change one's mind" },
  { level:"A2", es:"Esa es una buena idea", en:"That's a good idea", alts:["That is a good idea"], hint:"" },
  { level:"A2", es:"No tengo idea", en:"I have no idea", alts:["I´ve no idea"], hint:"" },
  { level:"A2", es:"¿Me estás bromeando?", en:"Are you kidding me?", alts:["Are you joking?"], hint:"" },
  { level:"A2", es:"Ya vuelvo", en:"I'll be right back", alts:["I'll be back"], hint:"right back = enseguida" },
  { level:"A2", es:"Siéntete como en casa", en:"Make yourself at home", alts:[], hint:"Frase fija" },
  { level:"A2", es:"Tengo prisa", en:"I´m in a hurry", alts:["I am in a hurry"], hint:"in a hurry, no 'with'" },
  { level:"A2", es:"¡Cuidado!", en:"Watch out!", alts:["Look out!","Be careful!"], hint:"" },
  { level:"A2", es:"Estoy en camino", en:"I´m on my way", alts:["I am on my way"], hint:"on my way" },
  { level:"A2", es:"Cálmate", en:"Calm down", alts:["Take it easy"], hint:"" },

  // ============ B1 ============
  { level:"B1", es:"Debí haberte llamado", en:"I should have called you", alts:["I should´ve called you"], hint:"should + have + participio = arrepentimiento" },
  { level:"B1", es:"Si yo fuera tú, aceptaría el trabajo", en:"If I were you, I´d take the job", alts:["If I were you, I would take the job"], hint:"Condicional 2: If + were + would" },
  { level:"B1", es:"Ha pasado mucho tiempo", en:"It´s been a long time", alts:["It has been a long time","Long time no see"], hint:"Present perfect impersonal" },
  { level:"B1", es:"Estoy acostumbrado a levantarme temprano", en:"I´m used to waking up early", alts:["I am used to waking up early"], hint:"used to + verbo-ing (costumbre)" },
  { level:"B1", es:"No soporto este clima", en:"I can´t stand this weather", alts:["I cannot stand this weather"], hint:"can´t stand = odiar" },
  { level:"B1", es:"Espero verte", en:"I look forward to seeing you", alts:["I´m looking forward to seeing you"], hint:"look forward TO + verbo-ing" },
  { level:"B1", es:"Eso no es lo que quise decir", en:"That's not what I meant", alts:["That is not what I meant"], hint:"mean → meant" },
  { level:"B1", es:"No podría estar más de acuerdo", en:"I couldn't agree more", alts:["I could not agree more"], hint:"Doble negativo idiomático = total acuerdo" },
  { level:"B1", es:"No es gran cosa", en:"It´s not a big deal", alts:["It´s no big deal"], hint:"" },
  { level:"B1", es:"Vayamos al grano", en:"Let's get to the point", alts:["Let's cut to the chase"], hint:"Idiomático" },
  { level:"B1", es:"Te debo una", en:"I owe you one", alts:[], hint:"owe = deber" },
  { level:"B1", es:"Vale la pena intentarlo", en:"It´s worth a try", alts:["It´s worth trying"], hint:"worth + sustantivo o gerundio" },
  { level:"B1", es:"Eso tiene sentido", en:"That makes sense", alts:["It makes sense"], hint:"make + sense, no 'have'" },
  { level:"B1", es:"No tuve otra opción", en:"I had no choice", alts:["I didn't have a choice"], hint:"" },
  { level:"B1", es:"Se me está acabando el tiempo", en:"I´m running out of time", alts:["I am running out of time"], hint:"run out OF" },
  { level:"B1", es:"No puedo creerlo", en:"I can´t believe it", alts:["I cannot believe it"], hint:"" },
  { level:"B1", es:"Ya era hora", en:"It´s about time", alts:["About time"], hint:"Idiomático" },
  { level:"B1", es:"No tengo ganas de salir", en:"I don´t feel like going out", alts:["I do not feel like going out"], hint:"feel like + verbo-ing" },
  { level:"B1", es:"Tengo que admitir", en:"I have to admit", alts:["I must admit"], hint:"" },
  { level:"B1", es:"Hasta donde sé", en:"As far as I know", alts:[], hint:"Frase fija" },
  { level:"B1", es:"Es pan comido", en:"It´s a piece of cake", alts:["It´s easy"], hint:"Modismo: muy fácil" },
  { level:"B1", es:"Estoy harto de esto", en:"I´m fed up with this", alts:["I am fed up with this","I´m sick of this"], hint:"fed up WITH" },
  { level:"B1", es:"Más vale prevenir que lamentar", en:"Better safe than sorry", alts:[], hint:"Refrán fijo" },
  { level:"B1", es:"Las cosas mejorarán", en:"Things will get better", alts:["Things are going to get better"], hint:"get + adjetivo = volverse" },
  { level:"B1", es:"Se me cruzó por la mente", en:"It crossed my mind", alts:[], hint:"Idiomático" },
  { level:"B1", es:"Tenía un presentimiento", en:"I had a feeling", alts:[], hint:"" },
  { level:"B1", es:"No lo tomes personal", en:"don´t take it personally", alts:["Do not take it personally"], hint:"personally con -ly" },
  { level:"B1", es:"Démoslo por terminado", en:"Let's call it a day", alts:[], hint:"Modismo" },
  { level:"B1", es:"Te aviso luego", en:"I'll get back to you", alts:["I will get back to you"], hint:"get back to = retomar contacto" },
  { level:"B1", es:"No es lo mío", en:"It´s not my cup of tea", alts:["It´s not my thing"], hint:"Modismo británico-americano" },
  { level:"B1", es:"Hablando del rey de Roma", en:"Speak of the devil", alts:[], hint:"Modismo fijo" },
  { level:"B1", es:"Me suena", en:"It rings a bell", alts:[], hint:"Modismo: me resulta familiar" },
  { level:"B1", es:"Lo estoy reconsiderando", en:"I´m having second thoughts", alts:["I am having second thoughts"], hint:"" },
  { level:"B1", es:"Es más fácil decirlo que hacerlo", en:"That's easier said than done", alts:[], hint:"" },
  { level:"B1", es:"No me malinterpretes", en:"don´t get me wrong", alts:[], hint:"" },
  { level:"B1", es:"Se me olvidó", en:"It slipped my mind", alts:["I forgot"], hint:"Modismo" },
  { level:"B1", es:"Mantenme al tanto", en:"Keep me posted", alts:["Keep me updated"], hint:"" },
  { level:"B1", es:"Ve al grano", en:"Cut to the chase", alts:[], hint:"" },
  { level:"B1", es:"Cuesta un ojo de la cara", en:"It costs an arm and a leg", alts:[], hint:"Modismo: muy caro" },
  { level:"B1", es:"Estoy en un aprieto", en:"I´m in a tough spot", alts:["I´m in trouble"], hint:"" },
].map((p, i) => ({ id: i + 1, ...p }));