// 120 frases A1/A2/B1 (inglés americano más usado)
// "alts": traducciones alternativas válidas que también se aceptan


export const PHRASES = [
  // ============ 1. Basic usage of 'I'm' ============
  { level:"A1", es:"Estoy listo", en:"I'm ready", alts:["I am ready"], hint:"Uso básico de I'm" },
  { level:"A1", es:"Tengo hambre", en:"I'm hungry", alts:["I am hungry"], hint:"En inglés se 'es' hambriento" },
  { level:"A1", es:"Estoy cansado", en:"I'm tired", alts:["I am tired"], hint:"" },
  { level:"A1", es:"Estoy emocionado por esto", en:"I'm excited 'bout this", alts:["I am excited about this"], hint:"Contracción de about a 'bout" },
  { level:"A1", es:"Soy desarrollador", en:"I'm a developer", alts:["I am a developer"], hint:"No olvides el artículo 'a'" },
  { level:"A2", es:"Estoy libre esta tarde", en:"I'm free this afternoon", alts:["I am free this afternoon"], hint:"" },
  { level:"A2", es:"Estoy preocupado por el examen", en:"I'm worried 'bout the test", alts:["I am worried about the exam"], hint:"" },
  { level:"B1", es:"Estoy a cargo del proyecto", en:"I'm in charge of the project", alts:["I am leading the project"], hint:"in charge of = a cargo de" },
  { level:"B1", es:"Estoy soltero por ahora", en:"I'm single for now", alts:["I am single at the moment"], hint:"" },
  { level:"B2", es:"Estoy escéptico sobre los resultados", en:"I'm skeptical 'bout the results", alts:["I am skeptical about the results"], hint:"Vocabulario avanzado para dar opiniones" },

  // ============ 2. Variations of 'I'm in/at/on' ============
  { level:"A1", es:"Estoy en el auto", en:"I'm in the car", alts:["I am inside the car"], hint:"'in' para espacios cerrados/vehículos pequeños" },
  { level:"A1", es:"Estoy en la oficina", en:"I'm at the office", alts:["I am in the office"], hint:"'at' para locaciones o lugares de trabajo" },
  { level:"A1", es:"Estoy en camino", en:"I'm on my way", alts:["I am on my way"], hint:"Frase fija: on my way" },
  { level:"A2", es:"Estoy en el autobús", en:"I'm on the bus", alts:["I am riding the bus"], hint:"'on' para transporte público donde puedes pararte" },
  { level:"A2", es:"Estoy en casa ahora mismo", en:"I'm at home right now", alts:["I am home right now"], hint:"" },
  { level:"A2", es:"Estoy en una reunión", en:"I'm in a meeting", alts:["I am in a meeting"], hint:"" },
  { level:"B1", es:"Estoy hablando por teléfono", en:"I'm on the phone", alts:["I am on a call"], hint:"on the phone = al teléfono" },
  { level:"B1", es:"Estoy en la computadora", en:"I'm on the computer", alts:["I am working on my laptop"], hint:"'on' para pantallas o dispositivos" },
  { level:"B2", es:"Estoy en una situación difícil", en:"I'm in a tough spot", alts:["I am in a difficult situation"], hint:"Modismo B2 para problemas" },
  { level:"B2", es:"Estoy a tiempo con el cronograma", en:"I'm on schedule", alts:["I am on time with the timeline"], hint:"Uso corporativo/técnico" },

  // ============ 3. I'm good at ============
  { level:"A2", es:"Soy bueno en inglés", en:"I'm good at English", alts:["I am good at speaking English"], hint:"good AT, nunca 'good in'" },
  { level:"A2", es:"Soy bueno en los deportes", en:"I'm good at sports", alts:[], hint:"" },
  { level:"B1", es:"Soy bueno programando", en:"I'm good at coding", alts:["I'm good at programming"], hint:"Después de 'at' va verbo en -ING" },
  { level:"B1", es:"Soy bueno cocinando", en:"I'm good at cooking", alts:[], hint:"" },
  { level:"B1", es:"Soy bueno con las matemáticas", en:"I'm good at math", alts:[], hint:"En USA se dice 'math', sin la 's'" },
  { level:"B1", es:"Soy bueno resolviendo problemas", en:"I'm good at solving problems", alts:[], hint:"" },
  { level:"B2", es:"Soy bueno multitareas", en:"I'm good at multitasking", alts:[], hint:"" },
  { level:"B2", es:"Soy bueno bajo presión", en:"I'm good at working under pressure", alts:[], hint:"" },
  { level:"B2", es:"Soy bueno negociando", en:"I'm good at negotiating", alts:[], hint:"" },
  { level:"B2", es:"Soy bueno arreglando bugs", en:"I'm good at fixing bugs", alts:[], hint:"Contexto técnico de programación" },

  // ============ 4. I'm + (verb) ============
  { level:"A1", es:"Estoy almorzando", en:"I'm having lunch", alts:["I'm eating lunch"], hint:"Los nativos usan más 'have lunch' que 'eat lunch'" },
  { level:"A1", es:"Estoy estudiando ahora", en:"I'm studying right now", alts:["I am studying now"], hint:"" },
  { level:"A1", es:"Estoy viendo una película", en:"I'm watching a movie", alts:["I am watching a film"], hint:"watch para pantallas" },
  { level:"A2", es:"Estoy trabajando desde casa", en:"I'm working from home", alts:["I'm remote working"], hint:"WFH (Working from home)" },
  { level:"A2", es:"Estoy aprendiendo React", en:"I'm learning React", alts:[], hint:"" },
  { level:"A2", es:"Estoy buscando mis llaves", en:"I'm looking for my keys", alts:[], hint:"look for = buscar" },
  { level:"B1", es:"Estoy mejorando mi pronunciación", en:"I'm improving my pronunciation", alts:[], hint:"" },
  { level:"B1", es:"Estoy arreglando este problema", en:"I'm fixing this issue", alts:["I'm fixing this problem"], hint:"issue = problema/asunto" },
  { level:"B2", es:"Estoy ejecutando las pruebas del sistema", en:"I'm running the system tests", alts:[], hint:"run = ejecutar (en desarrollo de software)" },
  { level:"B2", es:"Estoy analizando las tendencias del mercado", en:"I'm analyzing the market trends", alts:[], hint:"" },

  // ============ 5. I'm getting ============
  { level:"A2", es:"Me estoy cansando", en:"I'm getting tired", alts:["I am becoming tired"], hint:"get + adjetivo = volverse/ponerse" },
  { level:"A2", es:"Me estoy enfermando", en:"I'm getting sick", alts:[], hint:"" },
  { level:"A2", es:"Se está haciendo tarde", en:"I'm getting late", alts:["It's getting late"], hint:"" },
  { level:"B1", es:"Estoy mejorando en esto", en:"I'm getting better at this", alts:[], hint:"" },
  { level:"B1", es:"Me estoy acostumbrando al clima", en:"I'm getting used to the weather", alts:[], hint:"get used to = acostumbrarse a" },
  { level:"B1", es:"Me estoy estresando", en:"I'm getting stressed out", alts:[], hint:"stress out = estresarse demasiado" },
  { level:"B2", es:"Me estoy quedando sin paciencia", en:"I'm getting impatient", alts:[], hint:"" },
  { level:"B2", es:"Me estoy frustrando con este bug", en:"I'm getting frustrated with this bug", alts:[], hint:"" },
  { level:"B2", es:"Estoy entendiendo el concepto", en:"I'm getting the hang of it", alts:["I'm understanding the concept"], hint:"get the hang of it = agarrarle el truco a algo" },
  { level:"B2", es:"Me estoy quedando sin tiempo", en:"I'm getting low on time", alts:["I'm running out of time"], hint:"" },

  /* // ============ 6. I'm trying + (verb) ============
  { level:"A1", es:"Estoy intentando aprender", en:"I'm trying to learn", alts:["I am trying to learn"], hint:"try + to + verbo base" },
  { level:"A1", es:"Estoy intentando dormir", en:"I'm trying to sleep", alts:[], hint:"" },
  { level:"A2", es:"Estoy tratando de hablar más rápido", en:"I'm trying to speak faster", alts:[], hint:"" },
  { level:"A2", es:"Estoy intentando llamarte", en:"I'm trying to call ya", alts:["I am trying to call you"], hint:"you se reduce a 'ya'" },
  { level:"B1", es:"Estoy tratando de solucionar este bug", en:"I'm trying to fix this bug", alts:[], hint:"" },
  { level:"B1", es:"Estoy intentando concentrarme", en:"I'm trying to focus", alts:["I am trying to concentrate"], hint:"focus se usa muchísimo más" },
  { level:"B1", es:"Estoy tratando de ahorrar dinero", en:"I'm trying to save money", alts:[], hint:"" },
  { level:"B2", es:"Estoy tratando de pensar en inglés", en:"I'm trying to think in English", alts:[], hint:"" },
  { level:"B2", es:"Estoy tratando de balancear mi tiempo", en:"I'm trying to balance my time", alts:[], hint:"" },
  { level:"B2", es:"Estoy intentando descifrar este código", en:"I'm trying to figure out this code", alts:[], hint:"figure out = descifrar/entender" },

  // ============ 7. I'm gonna + (verb) ============
  { level:"A2", es:"Voy a comer", en:"I'm gonna eat", alts:["I'm going to eat"], hint:"gonna = going to" },
  { level:"A2", es:"Te voy a llamar luego", en:"I'm gonna call ya later", alts:["I am going to call you later"], hint:"" },
  { level:"A2", es:"Voy a comprar una laptop", en:"I'm gonna buy a laptop", alts:[], hint:"" },
  { level:"B1", es:"Voy a empezar un nuevo proyecto", en:"I'm gonna start a new project", alts:[], hint:"" },
  { level:"B1", es:"Voy a salir esta noche", en:"I'm gonna go out tonight", alts:[], hint:"" },
  { level:"B1", es:"Te voy a enviar el link", en:"I'm gonna text ya the link", alts:["I'm going to send you the link"], hint:"text = enviar por mensaje" },
  { level:"B2", es:"Voy a terminar esto mañana por la mañana", en:"I'm gonna finish this tomorrow morning", alts:[], hint:"" },
  { level:"B2", es:"Voy a revisar el código", en:"I'm gonna review the code", alts:[], hint:"" },
  { level:"B2", es:"Voy a tomar un descanso", en:"I'm gonna take a break", alts:[], hint:"" },
  { level:"B2", es:"Voy a dar lo mejor de mí", en:"I'm gonna do my best", alts:[], hint:"do my best = dar lo mejor" },

  // ============ 8. I have + (noun) ============
  { level:"A1", es:"Tengo una pregunta", en:"I have a question", alts:["I've got a question"], hint:"" },
  { level:"A1", es:"Tengo un carro", en:"I have a car", alts:["I've got a car"], hint:"" },
  { level:"A1", es:"Tengo una idea", en:"I have an idea", alts:[], hint:"" },
  { level:"A2", es:"Tengo una reunión ahora", en:"I have a meeting now", alts:["I've got a meeting now"], hint:"" },
  { level:"A2", es:"Tengo dolor de cabeza", en:"I have a headache", alts:[], hint:"" },
  { level:"A2", es:"Tengo mucho trabajo", en:"I have a lot of work", alts:["I've got tons of work"], hint:"" },
  { level:"B1", es:"Tengo una fecha límite mañana", en:"I have a deadline tomorrow", alts:[], hint:"deadline = fecha límite" },
  { level:"B1", es:"Tengo una sugerencia", en:"I have a suggestion", alts:[], hint:"" },
  { level:"B2", es:"Tengo sentimientos encontrados sobre esto", en:"I have mixed feelings 'bout this", alts:[], hint:"" },
  { level:"B2", es:"Tengo el presentimiento de que va a funcionar", en:"I have a feeling it's gonna work", alts:[], hint:"" },

  // ============ 9. I have + (past participle) ============
  { level:"A2", es:"Ya comí", en:"I've already eaten", alts:["I have already eaten"], hint:"Present perfect continuo de eat" },
  { level:"A2", es:"He visto esa película", en:"I've seen that movie", alts:[], hint:"" },
  { level:"A2", es:"Terminé mi trabajo", en:"I've finished my work", alts:[], hint:"" },
  { level:"B1", es:"He estado aquí antes", en:"I've been here before", alts:[], hint:"" },
  { level:"B1", es:"He vivido aquí por dos años", en:"I've lived here for two years", alts:[], hint:"" },
  { level:"B1", es:"Olvidé mi contraseña", en:"I've forgotten my password", alts:["I forgot my password"], hint:"" },
  { level:"B2", es:"He considerado cambiar mi estrategia", en:"I've considered changing my strategy", alts:[], hint:"" },
  { level:"B2", es:"Me he dado cuenta de que toma tiempo", en:"I've realized that it takes time", alts:[], hint:"" },
  { level:"B2", es:"He hecho esto un millón de veces", en:"I've done this a million times", alts:[], hint:"Hipérbole muy común" },
  { level:"B2", es:"Ya desplegué los cambios", en:"I've already deployed the changes", alts:[], hint:"Contexto dev" },

  // ============ 10. I used to + (verb) ============
  { level:"A2", es:"Solía jugar videojuegos", en:"I used to play video games", alts:[], hint:"used to = solía (hábitos pasados)" },
  { level:"A2", es:"Solía vivir en otra ciudad", en:"I used to live in another city", alts:[], hint:"" },
  { level:"A2", es:"Solía tener un gato", en:"I used to have a cat", alts:[], hint:"" },
  { level:"B1", es:"Solía levantarme temprano", en:"I used to wake up early", alts:[], hint:"" },
  { level:"B1", es:"Solía trabajar en una oficina", en:"I used to work in an office", alts:[], hint:"" },
  { level:"B1", es:"Solía ir al gimnasio todos los días", en:"I used to go to the gym every day", alts:[], hint:"" },
  { level:"B2", es:"Yo solía programar en Python", en:"I used to code in Python", alts:[], hint:"" },
  { level:"B2", es:"Antes no me gustaba el café", en:"I didn't use to like coffee", alts:[], hint:"Negativo: didn't use to" },
  { level:"B2", es:"Solía dudar de mis habilidades", en:"I used to doubt my skills", alts:[], hint:"" },
  { level:"B2", es:"Solía operar acciones, no opciones", en:"I used to trade stocks, not options", alts:[], hint:"Contexto financiero" },

  // ============ 11. I have to + (verb) ============
  { level:"A1", es:"Tengo que irme", en:"I have to go", alts:["I've got to go"], hint:"Obligación básica" },
  { level:"A1", es:"Tengo que estudiar", en:"I have to study", alts:[], hint:"" },
  { level:"A1", es:"Tengo que trabajar", en:"I have to work", alts:[], hint:"" },
  { level:"A2", es:"Tengo que comprar comida", en:"I have to buy groceries", alts:[], hint:"groceries = comida de supermercado" },
  { level:"A2", es:"Tengo que llamar a mi mamá", en:"I have to call my mom", alts:[], hint:"" },
  { level:"B1", es:"Tengo que terminar este reporte hoy", en:"I have to finish this report today", alts:[], hint:"" },
  { level:"B1", es:"Tengo que actualizar la app", en:"I have to update the app", alts:[], hint:"" },
  { level:"B2", es:"Tengo que admitir que tienes razón", en:"I have to admit you're right", alts:[], hint:"" },
  { level:"B2", es:"Tengo que solucionar este error de inmediato", en:"I have to fix this bug right away", alts:[], hint:"right away = de inmediato" },
  { level:"B2", es:"Tengo que tomar una decisión pronto", en:"I have to make a decision soon", alts:[], hint:"make a decision, no 'take'" },

  // ============ 12. I wanna + (verb) ============
  { level:"A1", es:"Quiero agua", en:"I wanna drink water", alts:["I want to drink water"], hint:"wanna = want to" },
  { level:"A1", es:"Quiero dormir", en:"I wanna sleep", alts:[], hint:"" },
  { level:"A2", es:"Quiero aprender inglés rápido", en:"I wanna learn English fast", alts:[], hint:"" },
  { level:"A2", es:"Quiero comprar una casa", en:"I wanna buy a house", alts:[], hint:"" },
  { level:"B1", es:"Quiero viajar este año", en:"I wanna travel this year", alts:[], hint:"" },
  { level:"B1", es:"Quiero mejorar mi código", en:"I wanna improve my code", alts:[], hint:"" },
  { level:"B1", es:"Quiero hablar con fluidez", en:"I wanna speak fluently", alts:[], hint:"" },
  { level:"B2", es:"Quiero dar el salto a un nuevo rol", en:"I wanna make the jump to a new role", alts:[], hint:"Modismo profesional" },
  { level:"B2", es:"Quiero automatizar este proceso", en:"I wanna automate this process", alts:[], hint:"" },
  { level:"B2", es:"Quiero ver de qué se trata esto", en:"I wanna see what this is 'bout", alts:[], hint:"" },

  // ============ 13. I gotta + (verb) ============
  { level:"A2", es:"Me tengo que ir", en:"I gotta go", alts:["I have got to go","I must go"], hint:"gotta = got to (obligación informal)" },
  { level:"A2", es:"Tengo que estudiar hoy", en:"I gotta study today", alts:[], hint:"" },
  { level:"A2", es:"Tengo que levantarme temprano", en:"I gotta wake up early", alts:[], hint:"" },
  { level:"B1", es:"Tengo que terminar esto ahora", en:"I gotta finish this now", alts:[], hint:"" },
  { level:"B1", es:"Tengo que hacer una llamada rápida", en:"I gotta make a quick call", alts:[], hint:"" },
  { level:"B1", es:"Tengo que revisar mis gráficos", en:"I gotta check my charts", alts:[], hint:"" },
  { level:"B2", es:"Tengo que ponerme al día con el trabajo", en:"I gotta catch up on work", alts:[], hint:"catch up on = ponerse al día con" },
  { level:"B2", es:"Tengo que encontrar una solución alternativa", en:"I gotta find a workaround", alts:[], hint:"workaround = solución alternativa temporal" },
  { level:"B2", es:"Tengo que admitir que está difícil", en:"I gotta admit it's tough", alts:[], hint:"tough = difícil/duro" },
  { level:"B2", es:"Tengo que ponerme las pilas hoy", en:"I gotta lock in today", alts:[], hint:"lock in = enfocarse al 100% (slang actual)" },

  // ============ 14. I would like to + (verb) ============
  { level:"A1", es:"Me gustaría un café", en:"I'd like to get a coffee", alts:["I would like to have a coffee"], hint:"I'd like = forma educada de pedir algo" },
  { level:"A2", es:"Me gustaría aprender más", en:"I'd like to learn more", alts:[], hint:"" },
  { level:"A2", es:"Me gustaría hacer una pregunta", en:"I'd like to ask a question", alts:[], hint:"" },
  { level:"B1", es:"Me gustaría agendar una reunión", en:"I'd like to schedule a meeting", alts:[], hint:"" },
  { level:"B1", es:"Me gustaría unirme al equipo", en:"I'd like to join the team", alts:[], hint:"" },
  { level:"B1", es:"Me gustaría probar esta función", en:"I'd like to test this feature", alts:[], hint:"feature = característica/función" },
  { level:"B2", es:"Me gustaría señalar algo", en:"I'd like to point out something", alts:[], hint:"point out = señalar/destacar" },
  { level:"B2", es:"Me gustaría hablar de nuestra estrategia", en:"I'd like to discuss our strategy", alts:[], hint:"discuss = debatir/analizar (no discutir de pelear)" },
  { level:"B2", es:"Me gustaría profundizar en este tema", en:"I'd like to dive deeper into this", alts:[], hint:"dive deeper = profundizar" },
  { level:"B2", es:"Me gustaría aclarar este punto", en:"I'd like to clarify this point", alts:[], hint:"" },

  // ============ 15. I plan to + (verb) ============
  { level:"A2", es:"Planeo estudiar esta noche", en:"I plan to study tonight", alts:[], hint:"plan + to + verbo base" },
  { level:"A2", es:"Planeo comprar una laptop mañana", en:"I plan to buy a laptop tomorrow", alts:[], hint:"" },
  { level:"B1", es:"Planeo lanzar la app el próximo mes", en:"I plan to launch the app next month", alts:[], hint:"" },
  { level:"B1", es:"Planeo ahorrar algo de dinero", en:"I plan to save some money", alts:[], hint:"" },
  { level:"B1", es:"Planeo tomar unas vacaciones pronto", en:"I plan to take a vacation soon", alts:[], hint:"" },
  { level:"B2", es:"Planeo optimizar el rendimiento del código", en:"I plan to optimize the code performance", alts:[], hint:"" },
  { level:"B2", es:"Planeo liquidar mi deuda antes de tiempo", en:"I plan to pay off my debt early", alts:[], hint:"pay off = liquidar una deuda" },
  { level:"B2", es:"Planeo automatizar mis alertas", en:"I plan to automate my alerts", alts:[], hint:"" },
  { level:"B2", es:"Planeo escalar este proyecto a producción", en:"I plan to scale this project to production", alts:[], hint:"" },
  { level:"B2", es:"Planeo expandir mi portafolio", en:"I plan to expand my portfolio", alts:[], hint:"" },

  // ============ 16. I've decided to + (verb) ============
  { level:"A2", es:"Decidí aprender inglés", en:"I've decided to learn English", alts:["I have decided to learn English"], hint:"Present perfect para decisiones recientes" },
  { level:"A2", es:"Decidí comprar este coche", en:"I've decided to buy this car", alts:[], hint:"" },
  { level:"B1", es:"Decidí cambiar mi rutina", en:"I've decided to change my routine", alts:[], hint:"" },
  { level:"B1", es:"Decidí empezar a ir al gimnasio", en:"I've decided to start going to the gym", alts:[], hint:"" },
  { level:"B1", es:"Decidí aceptar la oferta de trabajo", en:"I've decided to accept the job offer", alts:[], hint:"" },
  { level:"B2", es:"Decidí reescribir todo el componente", en:"I've decided to rewrite the whole component", alts:[], hint:"Contexto React" },
  { level:"B2", es:"Decidí cambiar de opinión sobre el plan", en:"I've decided to change my mind 'bout the plan", alts:[], hint:"" },
  { level:"B2", es:"Decidí dar un paso atrás y analizar las cosas", en:"I've decided to take a step back and analyze things", alts:[], hint:"take a step back = distanciarse para evaluar" },
  { level:"B2", es:"Decidí enfocarme en trading de opciones", en:"I've decided to focus on options trading", alts:[], hint:"" },
  { level:"B2", es:"Decidí actualizar mis herramientas de desarrollo", en:"I've decided to upgrade my dev tools", alts:[], hint:"" },

  // ============ 17. I was about to + (verb) ============
  { level:"A2", es:"Estaba a punto de llamarte", en:"I was 'bout to call ya", alts:["I was about to call you"], hint:"about to = a punto de" },
  { level:"A2", es:"Estaba a punto de comer", en:"I was 'bout to eat", alts:[], hint:"" },
  { level:"A2", es:"Estaba a punto de irme", en:"I was 'bout to leave", alts:[], hint:"" },
  { level:"B1", es:"Estaba a punto de enviar el correo", en:"I was 'bout to send the email", alts:[], hint:"" },
  { level:"B1", es:"Estaba a punto de cerrar la pestaña", en:"I was 'bout to close the tab", alts:[], hint:"" },
  { level:"B1", es:"Estaba a punto de decir eso", en:"I was 'bout to say that", alts:[], hint:"" },
  { level:"B2", es:"Estaba a punto de subir los cambios a GitHub", en:"I was 'bout to push the changes to GitHub", alts:[], hint:"push changes = subir cambios con git" },
  { level:"B2", es:"Estaba a punto de apagar mi laptop por el día", en:"I was 'bout to shut down my laptop for the day", alts:[], hint:"" },
  { level:"B2", es:"Estaba a punto de rendirme con este bug", en:"I was 'bout to give up on this bug", alts:[], hint:"give up on = rendirse con algo" },
  { level:"B2", es:"Estaba a punto de ejecutar el script", en:"I was 'bout to run the script", alts:[], hint:"" },

  // ============ 18. I didn't mean to + (verb) ============
  { level:"A2", es:"No fue mi intención hacer eso", en:"I didn't mean to do that", alts:[], hint:"didn't mean to = no fue mi intención" },
  { level:"A2", es:"No quise herir tus sentimientos", en:"I didn't mean to hurt your feelings", alts:[], hint:"" },
  { level:"B1", es:"No quise interrumpir", en:"I didn't mean to interrupt", alts:[], hint:"" },
  { level:"B1", es:"No fue mi intención causar problemas", en:"I didn't mean to cause any trouble", alts:[], hint:"" },
  { level:"B1", es:"No quise borrar ese archivo", en:"I didn't mean to delete that file", alts:[], hint:"" },
  { level:"B2", es:"No quise romper el diseño de la interfaz", en:"I didn't mean to break the UI layout", alts:[], hint:"UI layout = diseño de interfaz" },
  { level:"B2", es:"No quise dejarte fuera de la cadena de correos", en:"I didn't mean to leave ya out of the email loop", alts:[], hint:"leave out of the loop = dejar fuera de la información" },
  { level:"B2", es:"No quise pasar por alto este detalle", en:"I didn't mean to overlook this detail", alts:[], hint:"overlook = pasar por alto/ignorar sin querer" },
  { level:"B2", es:"No quise ofender a nadie", en:"I didn't mean to offend anyone", alts:[], hint:"" },
  { level:"B2", es:"No quise pisar tus talones con este proyecto", en:"I didn't mean to step on your toes with this project", alts:[], hint:"step on someone's toes = entrometerse en el terreno de otro" },

  // ============ 19. I don't have time to + (verb) ============
  { level:"A1", es:"No tengo tiempo para hablar", en:"I don't have time to talk", alts:[], hint:"" },
  { level:"A1", es:"No tengo tiempo para comer", en:"I don't have time to eat", alts:[], hint:"" },
  { level:"A2", es:"No tengo tiempo para ver la tele", en:"I don't have time to watch TV", alts:[], hint:"" },
  { level:"A2", es:"No tengo tiempo para salir hoy", en:"I don't have time to go out today", alts:[], hint:"" },
  { level:"B1", es:"No tengo tiempo para desperdiciar", en:"I don't have time to waste", alts:[], hint:"" },
  { level:"B1", es:"No tengo tiempo para lidiar con esto ahora", en:"I don't have time to deal with this right now", alts:[], hint:"deal with = lidiar con" },
  { level:"B2", es:"No tengo tiempo para revisar la documentación completa", en:"I don't have time to read the whole documentation", alts:[], hint:"" },
  { level:"B2", es:"No tengo tiempo para andar con rodeos", en:"I don't have time to beat around the bush", alts:[], hint:"Modismo: irse con rodeos" },
  { level:"B2", es:"No tengo tiempo para microgestionar las tareas", en:"I don't have time to micromanage tasks", alts:[], hint:"" },
  { level:"B2", es:"No tengo tiempo para refactorizar este componente antiguo", en:"I don't have time to refactor this legacy component", alts:[], hint:"legacy component = código antiguo/heredado" },

  // ============ 20. I promise not to + (verb) ============
  { level:"A2", es:"Prometo no llegar tarde", en:"I promise not to be late", alts:[], hint:"" },
  { level:"A2", es:"Prometo no decir nada", en:"I promise not to say anything", alts:[], hint:"" },
  { level:"B1", es:"Prometo no olvidar tu cumpleaños", en:"I promise not to forget your birthday", alts:[], hint:"" },
  { level:"B1", es:"Prometo no perder tus llaves", en:"I promise not to lose your keys", alts:[], hint:"" },
  { level:"B1", es:"Prometo no contarle a nadie el secreto", en:"I promise not to tell anyone the secret", alts:[], hint:"" },
  { level:"B2", es:"Prometo no arruinar la sorpresa", en:"I promise not to ruin the surprise", alts:[], hint:"" },
  { level:"B2", es:"Prometo no romper el código de producción", en:"I promise not to break production code", alts:[], hint:"" },
  { level:"B2", es:"Prometo no defraudar al equipo", en:"I promise not to let the team down", alts:[], hint:"let down = decepcionar/defraudar" },
  { level:"B2", es:"Prometo no quejarme más sobre el problema", en:"I promise not to complain 'bout the issue anymore", alts:[], hint:"" },
  { level:"B2", es:"Prometo no tomar riesgos innecesarios", en:"I promise not to take unnecessary risks", alts:[], hint:"" },

  // ============ 21. I'd rather + (verb) ============
  { level:"A2", es:"Prefiero quedarme en casa", en:"I'd rather stay home", alts:["I would rather stay at home"], hint:"I'd rather + verbo base (preferencia)" },
  { level:"A2", es:"Prefiero tomar café", en:"I'd rather drink coffee", alts:[], hint:"" },
  { level:"B1", es:"Prefiero no ir", en:"I'd rather not go", alts:[], hint:"Negativo: I'd rather NOT" },
  { level:"B1", es:"Prefiero trabajar solo", en:"I'd rather work alone", alts:[], hint:"" },
  { level:"B1", es:"Prefiero hablar de esto en persona", en:"I'd rather talk 'bout this in person", alts:[], hint:"" },
  { level:"B2", es:"Prefiero usar React antes que Angular", en:"I'd rather use React than Angular", alts:[], hint:"Comparación: I'd rather A than B" },
  { level:"B2", es:"Prefiero ir al grano", en:"I'd rather cut to the chase", alts:[], hint:"cut to the chase = ir al grano" },
  { level:"B2", es:"Prefiero tomar una decisión segura", en:"I'd rather play it safe", alts:[], hint:"play it safe = ir a lo seguro" },
  { level:"B2", es:"Prefiero pasar de esta oferta por ahora", en:"I'd rather pass on this offer for now", alts:[], hint:"pass on = dejar pasar/declinar" },
  { level:"B2", es:"Prefiero no arriesgar mi capital en esta operación", en:"I'd rather not risk my capital on this trade", alts:[], hint:"" },

  // ============ 22. I feel like + (verb-ing) ============
  { level:"A2", es:"Tengo ganas de comer pizza", en:"I feel like eating pizza", alts:[], hint:"feel like + verbo con -ING (antojo/ganas)" },
  { level:"A2", es:"Tengo ganas de ver una película", en:"I feel like watching a movie", alts:[], hint:"" },
  { level:"B1", es:"No tengo ganas de cocinar hoy", en:"I don't feel like cooking today", alts:[], hint:"" },
  { level:"B1", es:"Tengo ganas de tomar un descanso", en:"I feel like taking a break", alts:[], hint:"" },
  { level:"B1", es:"No tengo ganas de salir esta noche", en:"I don't feel like going out tonight", alts:[], hint:"" },
  { level:"B2", es:"Tengo ganas de tirar la toalla con este bug", en:"I feel like throwing in the towel with this bug", alts:[], hint:"throw in the towel = tirar la toalla (rendirse)" },
  { level:"B2", es:"Siento que estoy perdiendo mi tiempo", en:"I feel like I'm wasting my time", alts:[], hint:"feel like + sujeto + verbo = tener la impresión de que" },
  { level:"B2", es:"Siento que estamos en la misma página", en:"I feel like we're on the same page", alts:[], hint:"" },
  { level:"B2", es:"Tengo ganas de intentar algo diferente", en:"I feel like trying something different", alts:[], hint:"" },
  { level:"B2", es:"Siento que algo no anda bien aquí", en:"I feel like something's not right here", alts:[], hint:"" },

  // ============ 23. I can't help + (verb-ing) ============
  { level:"B1", es:"No puedo evitar pensar en eso", en:"I can't help thinking 'bout it", alts:[], hint:"can't help + -ING = no poder evitar algo" },
  { level:"B1", es:"No puedo evitar reírme", en:"I can't help laughing", alts:[], hint:"" },
  { level:"B1", es:"No puedo evitar preocuparme", en:"I can't help worrying", alts:[], hint:"" },
  { level:"B2", es:"No puedo evitar sentirme un poco frustrado", en:"I can't help feeling a bit frustrated", alts:[], hint:"" },
  { level:"B2", es:"No puedo evitar revisar mis gráficos cada 5 minutos", en:"I can't help checking my charts every 5 minutes", alts:[], hint:"" },
  { level:"B2", es:"No puedo evitar notar que hay un error de lógica", en:"I can't help noticing there's a logic error", alts:[], hint:"" },
  { level:"B2", es:"No puedo evitar sonreír cuando todo funciona", en:"I can't help smiling when everything works", alts:[], hint:"" },
  { level:"B2", es:"No puedo evitar dudar de este plan", en:"I can't help doubting this plan", alts:[], hint:"" },
  { level:"B2", es:"No puedo evitar comparar ambas soluciones", en:"I can't help comparing both solutions", alts:[], hint:"" },
  { level:"B2", es:"No puedo evitar preguntarme si hay una mejor manera", en:"I can't help wondering if there's a better way", alts:[], hint:"" },

  // ============ 24. I was busy + (verb-ing) ============
  { level:"A2", es:"Estaba ocupado estudiando", en:"I was busy studying", alts:[], hint:"busy + verbo con -ING directamente" },
  { level:"A2", es:"Estaba ocupado trabajando", en:"I was busy working", alts:[], hint:"" },
  { level:"A2", es:"Estaba ocupado limpiando mi cuarto", en:"I was busy cleaning my room", alts:[], hint:"" },
  { level:"B1", es:"Estaba ocupado preparando la presentación", en:"I was busy preparing the presentation", alts:[], hint:"" },
  { level:"B1", es:"Estaba ocupado respondiendo correos", en:"I was busy answering emails", alts:[], hint:"" },
  { level:"B1", es:"Estaba ocupado arreglando la base de datos", en:"I was busy fixing the database", alts:[], hint:"" },
  { level:"B2", es:"Estaba ocupado depurando la aplicación de React", en:"I was busy debugging the React app", alts:[], hint:"" },
  { level:"B2", es:"Estaba ocupado configurando los entornos de Git", en:"I was busy setting up the Git environments", alts:[], hint:"" },
  { level:"B2", es:"Estaba ocupado resolviendo conflictos de fusión", en:"I was busy resolving merge conflicts", alts:[], hint:"merge conflicts = conflictos al fusionar código en Git" },
  { level:"B2", es:"Estaba ocupado analizando la tendencia del SPY", en:"I was busy analyzing the SPY trend", alts:[], hint:"" },

  // ============ 25. I'm not used to + (verb-ing) ============
  { level:"B1", es:"No estoy acostumbrado a levantarme tan temprano", en:"I'm not used to waking up so early", alts:[], hint:"be not used to + -ING = no estar acostumbrado a" },
  { level:"B1", es:"No estoy acostumbrado a este clima", en:"I'm not used to this weather", alts:[], hint:"También acepta sustantivos directamente" },
  { level:"B1", es:"No estoy acostumbrado a hablar inglés todo el día", en:"I'm not used to speaking English all day", alts:[], hint:"" },
  { level:"B2", es:"No estoy acostumbrado a trabajar de forma remota", en:"I'm not used to working remotely", alts:[], hint:"" },
  { level:"B2", es:"No estoy acostumbrado a programar sin TypeScript", en:"I'm not used to coding without TypeScript", alts:[], hint:"" },
  { level:"B2", es:"No estoy acostumbrado a usar una Mac", en:"I'm not used to using a Mac", alts:[], hint:"" },
  { level:"B2", es:"No estoy acostumbrado a este tipo de flujo de trabajo", en:"I'm not used to this kind of workflow", alts:[], hint:"" },
  { level:"B2", es:"No estoy acostumbrado a tomar decisiones bajo tanta presión", en:"I'm not used to making decisions under so much pressure", alts:[], hint:"" },
  { level:"B2", es:"No estoy acostumbrado a leer código de otras personas", en:"I'm not used to reading other people's code", alts:[], hint:"" },
  { level:"B2", es:"No estoy acostumbrado a este nivel de volatilidad en el mercado", en:"I'm not used to this level of market volatility", alts:[], hint:"" },

  // ============ 26. I want you to + (verb) ============
  { level:"A2", es:"Quiero que vengas aquí", en:"I want ya to come here", alts:["I want you to come here"], hint:"I want you to + verbo = estructura para pedirle algo a alguien" },
  { level:"A2", es:"Quiero que escuches esto", en:"I want ya to listen to this", alts:[], hint:"" },
  { level:"A2", es:"Quiero que me ayudes", en:"I want ya to help me", alts:[], hint:"" },
  { level:"B1", es:"Quiero que revises este archivo", en:"I want ya to check this file", alts:[], hint:"" },
  { level:"B1", es:"Quiero que pruebes esta nueva función", en:"I want ya to test this new feature", alts:[], hint:"" },
  { level:"B1", es:"Quiero que me avises cuando termines", en:"I want ya to let me know when ya finish", alts:[], hint:"let me know = avísame/hazme saber" },
  { level:"B2", es:"Quiero que revises mi código en GitHub", en:"I want ya to review my pull request on GitHub", alts:[], hint:"pull request = solicitud de revisión de código" },
  { level:"B2", es:"Quiero que pienses fuera de la caja para esto", en:"I want ya to think outside the box for this", alts:[], hint:"" },
  { level:"B2", es:"Quiero que te enfoques en los detalles clave", en:"I want ya to focus on the key details", alts:[], hint:"" },
  { level:"B2", es:"Quiero que eches un vistazo a este gráfico de TradingView", en:"I want ya to take a look at this TradingView chart", alts:[], hint:"" },

  // ============ 27. I'm here to + (verb) ============
  { level:"A1", es:"Estoy aquí para ayudar", en:"I'm here to help", alts:[], hint:"I'm here to = propósito básico" },
  { level:"A1", es:"Estoy aquí para aprender", en:"I'm here to learn", alts:[], hint:"" },
  { level:"A2", es:"Estoy aquí para trabajar", en:"I'm here to work", alts:[], hint:"" },
  { level:"A2", es:"Estoy aquí para verte", en:"I'm here to see ya", alts:[], hint:"" },
  { level:"B1", es:"Estoy aquí para resolver el problema", en:"I'm here to solve the problem", alts:[], hint:"" },
  { level:"B1", es:"Estoy aquí para apoyar al equipo", en:"I'm here to support the team", alts:[], hint:"" },
  { level:"B2", es:"Estoy aquí para presentar los resultados de Six Sigma", en:"I'm here to present the Six Sigma results", alts:[], hint:"" },
  { level:"B2", es:"Estoy aquí para optimizar el rendimiento de nuestra aplicación", en:"I'm here to optimize our app performance", alts:[], hint:"" },
  { level:"B2", es:"Estoy aquí para aclarar cualquier malentendido", en:"I'm here to clear up any misunderstanding", alts:[], hint:"clear up = aclarar/resolver" },
  { level:"B2", es:"Estoy aquí para aprender a dominar las herramientas de análisis técnico", en:"I'm here to master the technical analysis tools", alts:[], hint:"" },

  // ============ 28. I have something + (verb) ============
  { level:"A2", es:"Tengo algo que decirte", en:"I have something to tell ya", alts:["I've got something to tell you"], hint:"something + to + verbo base" },
  { level:"A2", es:"Tengo algo para ti", en:"I have something for ya", alts:[], hint:"" },
  { level:"A2", es:"Tengo algo que mostrarte", en:"I have something to show ya", alts:[], hint:"" },
  { level:"B1", es:"Tengo algo que confesar", en:"I have something to confess", alts:[], hint:"" },
  { level:"B1", es:"Tengo algo que discutir contigo", en:"I have something to discuss with ya", alts:[], hint:"" },
  { level:"B1", es:"Tengo algo importante que hacer", en:"I have something important to do", alts:[], hint:"" },
  { level:"B2", es:"Tengo algo que podría solucionar este bug", en:"I have something that could fix this bug", alts:[], hint:"" },
  { level:"B2", es:"Tengo algo en mente para el nuevo diseño", en:"I have something in mind for the new layout", alts:[], hint:"have something in mind = tener algo pensado" },
  { level:"B2", es:"Tengo algo pendiente con mi gestor del proyecto", en:"I have something pending with my project manager", alts:[], hint:"" },
  { level:"B2", es:"Tengo algo que agregar a la reunión antes de terminar", en:"I have something to add to the meeting before we wrap up", alts:[], hint:"wrap up = dar por terminado/concluir" },

  // ============ 29. I'm looking forward to ============
  { level:"B1", es:"Espero con ansias la fiesta", en:"I'm looking forward to the party", alts:[], hint:"look forward to + sustantivo (entusiasmo por el futuro)" },
  { level:"B1", es:"Espero con ansias verte", en:"I'm looking forward to seeing ya", alts:[], hint:"Si pones un verbo después de 'to', va obligatoriamente con -ING" },
  { level:"B1", es:"Espero con ansias el fin de semana", en:"I'm looking forward to the weekend", alts:[], hint:"" },
  { level:"B1", es:"Espero con ansias tus comentarios", en:"I'm looking forward to your feedback", alts:[], hint:"feedback = comentarios/retroalimentación" },
  { level:"B2", es:"Espero con ansias unirme al equipo de desarrollo", en:"I'm looking forward to joining the dev team", alts:[], hint:"" },
  { level:"B2", es:"Espero con ansias lanzar la aplicación en producción", en:"I'm looking forward to launching the app in production", alts:[], hint:"" },
  { level:"B2", es:"Espero con ansias nuestra próxima reunión de sincronización", en:"I'm looking forward to our next sync meeting", alts:[], hint:"sync meeting = reunión de alineación/sincronización" },
  { level:"B2", es:"Espero con ansias obtener mi certificación de Six Sigma", en:"I'm looking forward to getting my Six Sigma certification", alts:[], hint:"" },
  { level:"B2", es:"Espero con ansias la próxima sesión de trading con mercado abierto", en:"I'm looking forward to the next live trading session", alts:[], hint:"" },
  { level:"B2", es:"Espero con ansias ver el resultado final de este proyecto", en:"I'm looking forward to seeing the final outcome of this project", alts:[], hint:"outcome = resultado final/conclusión" }, */
].map((p, i) => ({ id: i + 1, ...p }));


// export const PHRASES = [
//   // ============ A1 ============
//   { level:"A1", es:"Hola, ¿cómo estás?", en:"Hey, how's it going?", alts:["Hi, how are you?","Hello, how are you?"], hint:"Saludo casual con contracción" },
//   { level:"A1", es:"Te veo mañana por la mañana", en:"See ya tomorrow morning", alts:["I will see you tomorrow morning"], hint:"Reducción de see you a 'see ya'" },
//   { level:"A1", es:"Tengo una reunión mañana por la tarde", en:"I gotta meeting tomorrow afternoon", alts:["I have a meeting tomorrow afternoon"], hint:"'gotta' para indicar que tienes un compromiso agendado" },
//   { level:"A1", es:"¿Qué vas a hacer mañana por la noche?", en:"What you gonna do tomorrow night?", alts:["What are you going to do tomorrow night?"], hint:"En el habla rápida se omite el 'are' y 'going to' se vuelve 'gonna'" },
//   { level:"A1", es:"Solo soy un estudiante", en:"I'm just a student", alts:["I am only a student"], hint:"'just' se usa para limitar o simplificar algo" },
//   { level:"A1", es:"Solo dame un segundo", en:"Just give me a sec", alts:["Just give me a second"], hint:"'sec' es el acortamiento típico de second" },
//   { level:"A1", es:"Me llamo Juan", en:"My name's Juan", alts:["My name is Juan","I'm Juan"], hint:"Contracción nativa de name + is" },
//   { level:"A1", es:"Soy de Venezolano", en:"I'm from Venezuela", alts:["I am from Venezuela"], hint:"Origen → from" },
//   { level:"A1", es:"Mucho gusto", en:"Nice to meet you", alts:["Pleased to meet you","Good to meet you"], hint:"Conocer a alguien por primera vez" },
//   { level:"A1", es:"¿Cómo te llamas?", en:"What's your name?", alts:["What is your name?"], hint:"Preguntar el nombre con contracción" },
//   { level:"A1", es:"¿De dónde eres?", en:"Where are you from?", alts:["Where do you come from?"], hint:"Origen → where + from" },
//   { level:"A1", es:"¿Cuántos años tienes?", en:"How old are you?", alts:[], hint:"En inglés se 'es' la edad, no se 'tiene'" },
//   { level:"A1", es:"Tengo 25 años", en:"I'm 25", alts:["I'm 25 years old","I am 25"], hint:"Los nativos casi nunca dicen 'years old' al hablar" },
//   { level:"A1", es:"No entiendo", en:"I don't get it", alts:["I don't understand","I do not understand"], hint:"'Don't get it' es mucho más común al hablar" },
//   { level:"A1", es:"¿Puedes ayudarme?", en:"Can you help me?", alts:["Could you help me?"], hint:"Pedir ayuda con can/could" },
//   { level:"A1", es:"¿Qué hora es?", en:"What's the time?", alts:["What time is it?","Do you know what time it is?"], hint:"Forma corta y rápida" },
//   { level:"A1", es:"Buenos días", en:"Morning!", alts:["Good morning"], hint:"Los americanos suelen omitir el 'Good'" },
//   { level:"A1", es:"Buenas noches", en:"Night!", alts:["Good night"], hint:"Forma corta al despedirse" },
//   { level:"A1", es:"Muchas gracias", en:"Thanks a lot", alts:["Thank you so much","Thank you very much"], hint:"" },
//   { level:"A1", es:"De nada", en:"No problem", alts:["You're welcome","Don't mention it"], hint:"'No problem' o 'Anytime' se usan más que 'You're welcome'" },
//   { level:"A1", es:"Lo siento", en:"Sorry", alts:["I'm sorry","I am sorry"], hint:"" },
//   { level:"A1", es:"Disculpa", en:"Excuse me", alts:[], hint:"Para llamar la atención" },
//   { level:"A1", es:"Te amo", en:"I love you", alts:[], hint:"" },
//   { level:"A1", es:"Tengo hambre", en:"I'm hungry", alts:["I am hungry"], hint:"En inglés se 'es' hambriento" },
//   { level:"A1", es:"Tengo sed", en:"I'm thirsty", alts:["I am thirsty"], hint:"to be + thirsty" },
//   { level:"A1", es:"Estoy cansado", en:"I'm tired", alts:["I am tired"], hint:"" },
//   { level:"A1", es:"Tengo frío", en:"I'm cold", alts:["I am cold"], hint:"to be + cold" },
//   { level:"A1", es:"Tengo calor", en:"I'm hot", alts:["I am hot"], hint:"to be + hot" },
//   { level:"A1", es:"Tengo un hermano", en:"I have a brother", alts:["I've got a brother"], hint:"" },
//   { level:"A1", es:"Este es mi amigo", en:"This is my friend", alts:[], hint:"" },
//   { level:"A1", es:"Me gusta el café", en:"I like coffee", alts:[], hint:"like sin 'the'" },
//   { level:"A1", es:"No me gusta el pescado", en:"I don't like fish", alts:["I do not like fish"], hint:"" },
//   { level:"A1", es:"¿Dónde está el baño?", en:"Where's the bathroom?", alts:["Where is the bathroom?","Where's the restroom?"], hint:"" },
//   { level:"A1", es:"¿Cuánto cuesta?", en:"How much is it?", alts:["How much does it cost?"], hint:"" },
//   { level:"A1", es:"Quiero agua, por favor", en:"I'd like water, please", alts:["I want water, please"], hint:"" },
//   { level:"A1", es:"Soy estudiante", en:"I'm a student", alts:["I am a student"], hint:"Recuerda el 'a'" },
//   { level:"A1", es:"Trabajo en una oficina", en:"I work in an office", alts:["I work at an office"], hint:"in/at + office" },
//   { level:"A1", es:"Tengo dos gatos", en:"I have two cats", alts:["I've got two cats"], hint:"" },
//   { level:"A1", es:"Está lloviendo", en:"It's raining", alts:["It is raining"], hint:"It como sujeto del clima" },
//   { level:"A1", es:"Hace sol hoy", en:"It's sunny today", alts:["It is sunny today"], hint:"It + is + adjetivo de clima" },
//   { level:"A1", es:"Vivo en Nueva York", en:"I live in New York", alts:[], hint:"" },
//   { level:"A1", es:"Nos vemos mañana", en:"See you tomorrow", alts:[], hint:"" },
//   { level:"A1", es:"Hasta luego", en:"See ya later", alts:["See you later","See ya"], hint:"'See ya' es la reducción típica" },
//   { level:"A1", es:"Que tengas un buen día", en:"Have a good one!", alts:["Have a nice day","Have a good day"], hint:"'Have a good one' es ultra americano para cualquier momento" },
//   { level:"A1", es:"No sé", en:"I dunno", alts:["I don't know","I do not know"], hint:"'Dunno' es la reducción hablada de don't know" },

//   // ============ A2 ============
//   { level:"A2", es:"Voy a la tienda", en:"I'm gonna go to the store", alts:["I'm going to the store","I am going to the store"], hint:"Usa 'gonna go' en lugar de 'going to'" },
//   { level:"A2", es:"Por eso no quiero ir", en:"That's why I don't wanna go", alts:["That is why I do not want to go"], hint:"That's why = por eso / wanna = want to" },
//   { level:"A2", es:"Ella se mudó, por eso está feliz", en:"She moved, that's why she's happy", alts:["She moved, that is the reason why she is happy"], hint:"Estructura causa-efecto muy directa" },
//   { level:"A2", es:"El juego es pasado mañana", en:"The game's the day after tomorrow", alts:["The game is the day after tomorrow"], hint:"Contracción del sujeto con el verbo is" },
//   { level:"A2", es:"Tengo que entregar el proyecto pasado mañana", en:"I gotta turn in the project the day after tomorrow", alts:["I have to submit the project the day after tomorrow"], hint:"turn in = entregar (phrasal verb de software/escuela)" },
//   { level:"A2", es:"Llegué aquí anteayer", en:"I got here the day before yesterday", alts:["I arrived here the day before yesterday"], hint:"'get here' en pasado se usa más que 'arrive'" },
//   { level:"A2", es:"Ayer no, anteayer", en:"Not yesterday, the day before yesterday", alts:[], hint:"Frase corta de aclaración" },
//   { level:"A2", es:"Acabo de terminar mi tarea", en:"I just finished my homework", alts:["I have just finished my homework"], hint:"'just' en pasado simple indica una acción recién hecha" },
//   { level:"A2", es:"Tengo que trabajar mañana", en:"I gotta work tomorrow", alts:["I have to work tomorrow","I've got to work tomorrow"], hint:"have to = gotta (obligación)" },
//   { level:"A2", es:"¿Me trae la cuenta, por favor?", en:"Can I have the check, please?", alts:["Could I have the check, please?","The check, please"], hint:"En USA se dice 'check', no 'bill'" },
//   { level:"A2", es:"Estoy buscando la estación de tren", en:"I'm looking for the train station", alts:["I am looking for the train station"], hint:"look for = buscar" },
//   { level:"A2", es:"¿Qué significa esta palabra?", en:"What's this word mean?", alts:["What does this word mean?","What's the meaning of this word?"], hint:"En el habla rápida se contrae el 'does' u omite" },
//   { level:"A2", es:"¿Cómo se dice esto en inglés?", en:"How do you say this in English?", alts:[], hint:"Pregunta con 'do you' (impersonal)" },
//   { level:"A2", es:"Llevo dos días aquí", en:"I've been here for two days", alts:["I have been here for two days"], hint:"Present perfect + for" },
//   { level:"A2", es:"Me gustaría un café, por favor", en:"I'd like a coffee, please", alts:["I would like a coffee, please"], hint:"Más educado que 'I want'" },
//   { level:"A2", es:"¿Podrías repetir, por favor?", en:"Could you repeat that, please?", alts:["Can you repeat that, please?"], hint:"Could = más educado" },
//   { level:"A2", es:"Olvidé mis llaves", en:"I forgot my keys", alts:["I've forgotten my keys"], hint:"Pasado simple de forget" },
//   { level:"A2", es:"Perdí mi teléfono", en:"I lost my phone", alts:["I've lost my phone"], hint:"Pasado simple de lose" },
//   { level:"A2", es:"Es mi turno", en:"It's my turn", alts:["It is my turn"], hint:"" },
//   { level:"A2", es:"No te preocupes", en:"Don't worry about it", alts:["Don't worry about it","Don't worry"], hint:"Reducción de about a 'bout" },
//   { level:"A2", es:"Solo estoy bromeando", en:"I'm just kidding", alts:["I'm only kidding","I'm just joking"], hint:"" },
//   { level:"A2", es:"Eso suena genial", en:"Sounds great!", alts:["That sounds great","That sounds awesome"], hint:"Suelen omitir el 'That' al inicio" },
//   { level:"A2", es:"Lo pensaré", en:"I'll think about it", alts:["I will think about it"], hint:"think + about" },
//   { level:"A2", es:"Depende de ti", en:"It's up to you", alts:["It depends on you"], hint:"'It's up to you' es mucho más común" },
//   { level:"A2", es:"Estoy de acuerdo contigo", en:"I agree with you", alts:[], hint:"agree WITH" },
//   { level:"A2", es:"No estoy de acuerdo", en:"I disagree", alts:["I don't agree"], hint:"" },
//   { level:"A2", es:"No importa", en:"It doesn't matter", alts:["It does not matter"], hint:"" },
//   { level:"A2", es:"Quizás después", en:"Maybe later", alts:["Perhaps later"], hint:"" },
//   { level:"A2", es:"¿Qué estás haciendo?", en:"What are you doing?", alts:["What you doing?"], hint:"Presente continuo en pregunta" },
//   { level:"A2", es:"Estoy viendo la tele", en:"I'm watching TV", alts:["I am watching TV"], hint:"watch para tele/películas" },
//   { level:"A2", es:"Fui a la playa ayer", en:"I went to the beach yesterday", alts:[], hint:"Pasado simple de go" },
//   { level:"A2", es:"Te llamará después", en:"I'll call you back", alts:["I will call you back"], hint:"call back = devolver llamada" },
//   { level:"A2", es:"¿Estás listo?", en:"Are you ready?", alts:[], hint:"" },
//   { level:"A2", es:"¡Apúrate!", en:"Hurry up!", alts:[], hint:"" },
//   { level:"A2", es:"Tómate tu tiempo", en:"Take your time", alts:[], hint:"Expresión idiomática" },
//   { level:"A2", es:"Tú decides", en:"It's up to you", alts:["It is up to you"], hint:"" },
//   { level:"A2", es:"Déjame pensar", en:"Let me think", alts:[], hint:"let + me + verbo base" },
//   { level:"A2", es:"Cambié de opinión", en:"I changed my mind", alts:["I've changed my mind"], hint:"change one's mind" },
//   { level:"A2", es:"Esa es una buena idea", en:"That's a good idea", alts:["That is a good idea"], hint:"" },
//   { level:"A2", es:"No tengo idea", en:"I have no idea", alts:["I've no idea"], hint:"" },
//   { level:"A2", es:"¿Me estás bromeando?", en:"Are you kidding me?", alts:["Are you joking?"], hint:"" },
//   { level:"A2", es:"Ya vuelvo", en:"I'll be right back", alts:["I'll be back"], hint:"right back = enseguida" },
//   { level:"A2", es:"Siéntete como en casa", en:"Make yourself at home", alts:[], hint:"Frase fija" },
//   { level:"A2", es:"Tengo prisa", en:"I'm in a hurry", alts:["I am in a hurry"], hint:"in a hurry, no 'with'" },
//   { level:"A2", es:"¡Cuidado!", en:"Watch out!", alts:["Look out!","Be careful!"], hint:"" },
//   { level:"A2", es:"Estoy en camino", en:"I'm on my way", alts:["I am on my way"], hint:"on my way" },
//   { level:"A2", es:"Cálmate", en:"Calm down", alts:["Take it easy"], hint:"" },
//   { level:"A2", es:"¿Cómo van las cosas?", en:"How’s it going?", alts:["How is it going?","How's everything?"], hint:"Saludo conversacional muy común" },
//   { level:"A2", es:"¿A qué te dedicas?", en:"What do you do?", alts:["What's your job?","What do you do for a living?"], hint:"Se refiere a ocupación o profesión" },
//   { level:"A2", es:"Suena bien", en:"Sounds good", alts:["That sounds good","Sounds like a plan"], hint:"Aceptación rápida de una propuesta" },
//   { level:"A2", es:"Qué bien", en:"That’s nice", alts:["That is nice","That's great"], hint:"Reacción positiva amigable" },
//   { level:"A2", es:"Déjame ver", en:"Let me see", alts:["Let me check"], hint:"Se usa también para ganar tiempo al pensar" },

//   // ============ B1 ============
//   { level:"B1", es:"Debí haberte llamado", en:"I should've called you", alts:["I should have called you"], hint:"should've es la contracción hablada estándar" },
//   { level:"B2", es:"No podemos lanzar la app pasado mañana; no está lista", en:"We can't launch the app the day after tomorrow; it's not ready", alts:["We cannot deploy the application the day after tomorrow"], hint:"launch/deploy = lanzar/desplegar software" },
//   { level:"B2", es:"Perdimos los servidores anteayer, por eso el sitio cayó", en:"We lost the servers the day before yesterday, that's why the site went down", alts:["The website crashed because we lost the servers"], hint:"go down = caerse (un sistema o sitio web)" },
//   { level:"B2", es:"Además de aprender inglés, él programa en React", en:"Beside learning English, he codes in React", alts:["In addition to learning English, he develops in React"], hint:"Beside + gerundio (learning) para añadir información" },
//   { level:"B1", es:"Por eso renuncié a mi trabajo", en:"That's why I quit my job", alts:["That is the reason why I left my employment"], hint:"quit = renunciar / dejar" },
//   { level:"B1", es:"Estaba lloviendo anteayer por la noche", en:"It was raining the day before last night", alts:[], hint:"Pasado continuo para describir el clima" },
//   { level:"B1", es:"Te envié el correo anteayer por la noche", en:"I sent ya the email the day before last night", alts:["I sent you the email two nights ago"], hint:"'two nights ago' es una alternativa común para esta frase" },
//   { level:"B1", es:"¿Dónde estabas anteayer por la noche?", en:"Where're you the night before last?", alts:["Where were you the night before last?"], hint:"'Where're you' es la contracción nativa de where + were" },
//   { level:"B1", es:"Además de eso, todo está bien", en:"Beside that, everything's fine", alts:["Besides that, everything is okay"], hint:"Beside/Besides se usan de forma intercambiable al inicio" },
//   { level:"B1", es:"Siéntate al lado de mí", en:"Sit down beside me", alts:["Sit next to me"], hint:"Beside como preposición de lugar (al lado de)" },
//   { level:"B1", es:"Si yo fuera tú, aceptaría el trabajo", en:"If I were you, I'd take the job", alts:["If I were you, I would take the job"], hint:"Condicional 2: If + were + would" },
//   { level:"B1", es:"Ha pasado mucho tiempo", en:"It's been a long time", alts:["It has been a long time","Long time no see"], hint:"Present perfect impersonal" },
//   { level:"B1", es:"Estoy acostumbrado a levantarme temprano", en:"I'm used to waking up early", alts:["I am used to waking up early"], hint:"used to + verbo-ing (costumbre)" },
//   { level:"B1", es:"No soporto este clima", en:"I can't stand this weather", alts:["I cannot stand this weather"], hint:"can't stand = odiar" },
//   { level:"B1", es:"Espero verte", en:"I'm looking forward to seeing you", alts:["I look forward to seeing you"], hint:"La forma continua se usa más de forma casual" },
//   { level:"B1", es:"Eso no es lo que quise decir", en:"That's not what I meant", alts:["That is not what I meant"], hint:"mean → meant" },
//   { level:"B1", es:"No podría estar más de acuerdo", en:"I couldn't agree more", alts:["I could not agree more"], hint:"Doble negativo idiomático = total acuerdo" },
//   { level:"B1", es:"No es gran cosa", en:"It's no big deal", alts:["It's not a big deal"], hint:"'No big deal' acorta aún más la frase" },
//   { level:"B1", es:"Vayamos al grano", en:"Let's get to the point", alts:["Let's cut to the chase"], hint:"Idiomático" },
//   { level:"B1", es:"Te debo una", en:"I owe you one", alts:[], hint:"owe = deber" },
//   { level:"B1", es:"Vale la pena intentarlo", en:"It's worth a try", alts:["It's worth trying"], hint:"worth + sustantivo o gerundio" },
//   { level:"B1", es:"Eso tiene sentido", en:"That makes sense", alts:["It makes sense"], hint:"make + sense, no 'have'" },
//   { level:"B1", es:"No tuve otra opción", en:"I had no choice", alts:["I didn't have a choice"], hint:"" },
//   { level:"B1", es:"Se me está acabando el tiempo", en:"I'm running out of time", alts:["I am running out of time"], hint:"run out OF" },
//   { level:"B1", es:"No puedo creerlo", en:"I can't believe it", alts:["I cannot believe it"], hint:"" },
//   { level:"B1", es:"Ya era hora", en:"It's about time", alts:["About time"], hint:"Idiomático" },
//   { level:"B1", es:"No tengo ganas de salir", en:"I don't feel like going out", alts:["I do not feel like going out"], hint:"feel like + verbo-ing" },
//   { level:"B1", es:"Tengo que admitir", en:"I have to admit", alts:["I must admit"], hint:"" },
//   { level:"B1", es:"Hasta donde sé", en:"As far as I know", alts:[], hint:"Frase fija" },
//   { level:"B1", es:"Es pan comido", en:"It's a piece of cake", alts:["It's easy"], hint:"Modismo: muy fácil" },
//   { level:"B1", es:"Estoy harto de esto", en:"I'm fed up with this", alts:["I am fed up with this","I'm sick of this"], hint:"fed up WITH" },
//   { level:"B1", es:"Más vale prevenir que lamentar", en:"Better safe than sorry", alts:[], hint:"Refrán fijo" },
//   { level:"B1", es:"Things'll get better", en:"Things will get better", alts:["Things are going to get better"], hint:"Contracción de un sustantivo plural con will" },
//   { level:"B1", es:"Se me cruzó por la mente", en:"It crossed my mind", alts:[], hint:"Idiomático" },
//   { level:"B1", es:"Tenía un presentimiento", en:"I had a feeling", alts:[], hint:"" },
//   { level:"B1", es:"No lo tomes personal", en:"Don't take it personally", alts:["Do not take it personally"], hint:"personally con -ly" },
//   { level:"B1", es:"Démoslo por terminado", en:"Let's call it a day", alts:[], hint:"Modismo" },
//   { level:"B1", es:"Te aviso luego", en:"I'll get back to you", alts:["I will get back to you"], hint:"get back to = retomar contacto" },
//   { level:"B1", es:"No es lo mío", en:"It's not my cup of tea", alts:["It's not my thing"], hint:"Modismo británico-americano" },
//   { level:"B1", es:"Hablando del rey de Roma", en:"Speak of the devil", alts:[], hint:"Modismo fijo" },
//   { level:"B1", es:"Me suena", en:"It rings a bell", alts:[], hint:"Modismo: me resulta familiar" },
//   { level:"B1", es:"Lo estoy reconsiderando", en:"I'm having second thoughts", alts:["I am having second thoughts"], hint:"" },
//   { level:"B1", es:"Es más fácil decirlo que hacerlo", en:"That's easier said than done", alts:[], hint:"" },
//   { level:"B1", es:"No me malinterpretes", en:"Don't get me wrong", alts:[], hint:"" },
//   { level:"B1", es:"Se me olvidó", en:"It slipped my mind", alts:["I forgot"], hint:"Modismo" },
//   { level:"B1", es:"Mantenme al tanto", en:"Keep me posted", alts:["Keep me updated"], hint:"" },
//   { level:"B1", es:"Ve al grano", en:"Cut to the chase", alts:[], hint:"" },
//   { level:"B1", es:"Cuesta un ojo de la cara", en:"It costs an arm and a leg", alts:[], hint:"Modismo: muy caro" },
//   { level:"B1", es:"Estoy en un aprieto", en:"I'm in a tough spot", alts:["I'm in trouble"], hint:"" },
//   { level:"B1", es:"Voy a...", en:"I’m gonna", alts:["I'm going to"], hint:"Reducción informal de 'going to' para futuro" },
//   { level:"B1", es:"Quiero...", en:"I wanna…", alts:["I want to"], hint:"Reducción informal de 'want to'" },
//   { level:"B1", es:"Me tengo que ir", en:"I gotta go", alts:["I have to go","I've got to go"], hint:"Reducción de '(have) got to go'" },
//   { level:"B1", es:"¿Sabes a qué me refiero?", en:"You know what I mean?", alts:["Do you know what I mean?","Know what I mean?"], hint:"Para confirmar si el otro te entiende" },

//   // ============ B2 ============
//   { level:"B2", es:"Para ser honesto", en:"To be completely honest", alts:["To be fair","To tell you the truth"], hint:"Para dar una opinión sincera o suavizar una crítica" },
//   { level:"B2", es:"Toma eso con pinzas", en:"Take that with a grain of salt", alts:["Take it with a grain of salt"], hint:"Modismo: no te lo tomes tan en serio o literal" },
//   { level:"B2", es:"A fin de cuentas", en:"At the end of the day", alts:["When all is said and done"], hint:"Expresión para resumir el punto más importante" },
//   { level:"B2", es:"Organicemos una reunión breve", en:"Let's touch base", alts:["Let's sync up"], hint:"Inglés corporativo muy usado para reconectar brevemente" },
//   { level:"B2", es:"Estamos en la misma página", en:"We're on the same page", alts:["We are on the same page"], hint:"Estar de acuerdo con los objetivos o planes" },
//   { level:"B2", es:"Pensemos fuera de la caja", en:"Let's think outside the box", alts:[], hint:"Tener ideas creativas e innovadoras" },
//   { level:"B2", es:"Ponerse al día", en:"To catch up", alts:["Let's catch up"], hint:"Reunirse con alguien para saber qué ha pasado en su vida" },
//   { level:"B2", es:"No es física cuántica", en:"It's not rocket science", alts:["It is not rocket science"], hint:"Modismo: no es tan difícil de entender" },
//   { level:"B2", es:"Por si acaso", en:"Just in case", alts:["As a precaution"], hint:"" },
//   { level:"B2", es:"De la nada", en:"Out of the blue", alts:["All of a sudden"], hint:"Algo que pasa de manera completamente inesperada" },
//   { level:"B2", es:"Estar abrumado de trabajo", en:"I'm snowed under", alts:["I'm swamped","I'm overloaded"], hint:"Modismo muy usado cuando tienes demasiadas tareas" },
//   { level:"B2", es:"Hasta ahora todo va bien", en:"So far, so good", alts:[], hint:"Frase fija muy común para reportar progreso" },
//   { level:"B2", es:"Dejar los rodeos", en:"Stop beating around the bush", alts:["Don't beat around the bush"], hint:"Hablar directamente de un tema incómodo" },
//   { level:"B2", es:"Hacer memoria", en:"Jog my memory", alts:["Refresh my memory"], hint:"Ayudar a recordar algo: 'That jogs my memory'" },
//   { level:"B2", es:"A largo plazo", en:"In the long run", alts:["Over time"], hint:"Mirando hacia el futuro distante" },
//   { level:"B2", es:"Me di cuenta de que", en:"I came to realize that", alts:["I realized that"], hint:"Estructura más avanzada para denotar un descubrimiento personal" },
//   { level:"B2", es:"Pospongamos esto", en:"Let's take a rain check", alts:["Let's postpone it"], hint:"Modismo para rechazar un plan educadamente prometiendo hacerlo después" },
//   { level:"B2", es:"Aprenderse los trucos/procesos", en:"Learn the ropes", alts:[], hint:"Aprender cómo se hace un trabajo o tarea nueva" },
//   { level:"B2", es:"Tener sentimientos encontrados", en:"I have mixed feelings", alts:["I've got mixed feelings"], hint:"Sentir cosas positivas y negativas a la vez sobre algo" },
//   { level:"B2", es:"Bajo el radar", en:"Under the radar", alts:[], hint:"Hacer algo de forma discreta o que pasa desapercibido" },
// ].map((p, i) => ({ id: i + 1, ...p }));
// export const PHRASES = [
//   // ============ A1 ============
//   { level:"A1", es:"Hola, ¿cómo estás?", en:"Hi, how are you?", alts:["Hello, how are you?","Hey, how are you?"], hint:"Saludo casual con pregunta" },
//   { level:"A1", es:"Me llamo Juan", en:"My name is Juan", alts:["I'm Juan","I am Juan"], hint:"Presentarse" },
//   { level:"A1", es:"Soy de Venezolano", en:"I'm from Venezolano", alts:["I am from Venezolano"], hint:"Origen → from" },
//   { level:"A1", es:"Mucho gusto", en:"Nice to meet you", alts:["Pleased to meet you","Good to meet you"], hint:"Conocer a alguien por primera vez" },
//   { level:"A1", es:"¿Cómo te llamas?", en:"What's your name?", alts:["What is your name?"], hint:"Preguntar el nombre" },
//   { level:"A1", es:"¿De dónde eres?", en:"Where are you from?", alts:["Where do you come from?"], hint:"Origen → where + from" },
//   { level:"A1", es:"¿Cuántos años tienes?", en:"How old are you?", alts:[], hint:"En inglés se 'es' la edad, no se 'tiene'" },
//   { level:"A1", es:"Tengo 25 años", en:"I'm 25 years old", alts:["I am 25","I'm 25"], hint:"Usa to be, no to have" },
//   { level:"A1", es:"No entiendo", en:"I don't understand", alts:["I do not understand"], hint:"Negación con don't" },
//   { level:"A1", es:"¿Puedes ayudarme?", en:"Can you help me?", alts:["Could you help me?"], hint:"Pedir ayuda con can/could" },
//   { level:"A1", es:"¿Qué hora es?", en:"What time is it?", alts:["What's the time?","Do you know what time it is?"], hint:"Inversión: time + is + it" },
//   { level:"A1", es:"Buenos días", en:"Good morning", alts:[], hint:"Solo en la mañana" },
//   { level:"A1", es:"Buenas noches", en:"Good night", alts:[], hint:"Para despedirse de noche" },
//   { level:"A1", es:"Muchas gracias", en:"Thank you very much", alts:["Thanks a lot","Thank you so much"], hint:"" },
//   { level:"A1", es:"De nada", en:"You're welcome", alts:["No problem","Don't mention it"], hint:"" },
//   { level:"A1", es:"Lo siento", en:"I'm sorry", alts:["I am sorry","Sorry"], hint:"" },
//   { level:"A1", es:"Disculpa", en:"Excuse me", alts:[], hint:"Para llamar la atención" },
//   { level:"A1", es:"Te amo", en:"I love you", alts:[], hint:"" },
//   { level:"A1", es:"Tengo hambre", en:"I'm hungry", alts:["I am hungry"], hint:"En inglés se 'es' hambriento" },
//   { level:"A1", es:"Tengo sed", en:"I'm thirsty", alts:["I am thirsty"], hint:"to be + thirsty" },
//   { level:"A1", es:"Estoy cansado", en:"I'm tired", alts:["I am tired"], hint:"" },
//   { level:"A1", es:"Tengo frío", en:"I'm cold", alts:["I am cold"], hint:"to be + cold" },
//   { level:"A1", es:"Tengo calor", en:"I'm hot", alts:["I am hot"], hint:"to be + hot" },
//   { level:"A1", es:"Tengo un hermano", en:"I have a brother", alts:["I've got a brother"], hint:"" },
//   { level:"A1", es:"Este es mi amigo", en:"This is my friend", alts:[], hint:"" },
//   { level:"A1", es:"Me gusta el café", en:"I like coffee", alts:[], hint:"like sin 'the'" },
//   { level:"A1", es:"No me gusta el pescado", en:"I don't like fish", alts:["I do not like fish"], hint:"" },
//   { level:"A1", es:"¿Dónde está el baño?", en:"Where is the bathroom?", alts:["Where's the bathroom?","Where's the restroom?"], hint:"" },
//   { level:"A1", es:"¿Cuánto cuesta?", en:"How much is it?", alts:["How much does it cost?"], hint:"" },
//   { level:"A1", es:"Quiero agua, por favor", en:"I want water, please", alts:["I'd like water, please"], hint:"" },
//   { level:"A1", es:"Soy estudiante", en:"I'm a student", alts:["I am a student"], hint:"Recuerda el 'a'" },
//   { level:"A1", es:"Trabajo en una oficina", en:"I work in an office", alts:["I work at an office"], hint:"in/at + office" },
//   { level:"A1", es:"Tengo dos gatos", en:"I have two cats", alts:["I've got two cats"], hint:"" },
//   { level:"A1", es:"Está lloviendo", en:"It's raining", alts:["It is raining"], hint:"It como sujeto del clima" },
//   { level:"A1", es:"Hace sol hoy", en:"It's sunny today", alts:["It is sunny today"], hint:"It + is + adjetivo de clima" },
//   { level:"A1", es:"Vivo en Nueva York", en:"I live in New York", alts:[], hint:"" },
//   { level:"A1", es:"Nos vemos mañana", en:"See you tomorrow", alts:[], hint:"" },
//   { level:"A1", es:"Hasta luego", en:"See you later", alts:["See ya"], hint:"" },
//   { level:"A1", es:"Que tengas un buen día", en:"Have a nice day", alts:["Have a good day"], hint:"" },
//   { level:"A1", es:"No sé", en:"I don't know", alts:["I do not know"], hint:"" },

//   // ============ A2 ============
//   { level:"A2", es:"Voy a la tienda", en:"I'm going to the store", alts:["I am going to the store","I'm going to the shop"], hint:"Presente continuo para acción ahora" },
//   { level:"A2", es:"Tengo que trabajar mañana", en:"I have to work tomorrow", alts:["I've got to work tomorrow"], hint:"have to = obligación" },
//   { level:"A2", es:"¿Me trae la cuenta, por favor?", en:"Can I have the check, please?", alts:["Could I have the check, please?","The check, please"], hint:"En USA se dice 'check', no 'bill'" },
//   { level:"A2", es:"Estoy buscando la estación de tren", en:"I'm looking for the train station", alts:["I am looking for the train station"], hint:"look for = buscar" },
//   { level:"A2", es:"¿Qué significa esta palabra?", en:"What does this word mean?", alts:["What's the meaning of this word?"], hint:"Auxiliar 'does' antes del sujeto" },
//   { level:"A2", es:"¿Cómo se dice esto en inglés?", en:"How do you say this in English?", alts:[], hint:"Pregunta con 'do you' (impersonal)" },
//   { level:"A2", es:"Llevo dos días aquí", en:"I've been here for two days", alts:["I have been here for two days"], hint:"Present perfect + for" },
//   { level:"A2", es:"Me gustaría un café, por favor", en:"I'd like a coffee, please", alts:["I would like a coffee, please"], hint:"Más educado que 'I want'" },
//   { level:"A2", es:"¿Podrías repetir, por favor?", en:"Could you repeat that, please?", alts:["Can you repeat that, please?"], hint:"Could = más educado" },
//   { level:"A2", es:"Olvidé mis llaves", en:"I forgot my keys", alts:["I've forgotten my keys"], hint:"Pasado simple de forget" },
//   { level:"A2", es:"Perdí mi teléfono", en:"I lost my phone", alts:["I've lost my phone"], hint:"Pasado simple de lose" },
//   { level:"A2", es:"Es mi turno", en:"It's my turn", alts:["It is my turn"], hint:"" },
//   { level:"A2", es:"No te preocupes", en:"Don't worry about it", alts:["Don't worry"], hint:"Imperativo negativo" },
//   { level:"A2", es:"Solo estoy bromeando", en:"I'm just kidding", alts:["I'm only kidding","I'm just joking"], hint:"" },
//   { level:"A2", es:"Eso suena genial", en:"That sounds great", alts:["That sounds awesome","That sounds amazing"], hint:"sound + adjetivo" },
//   { level:"A2", es:"Lo pensaré", en:"I'll think about it", alts:["I will think about it"], hint:"think + about" },
//   { level:"A2", es:"Depende de ti", en:"It depends on you", alts:["It's up to you"], hint:"depend ON, no 'of'" },
//   { level:"A2", es:"Estoy de acuerdo contigo", en:"I agree with you", alts:[], hint:"agree WITH" },
//   { level:"A2", es:"No estoy de acuerdo", en:"I disagree", alts:["I don't agree"], hint:"" },
//   { level:"A2", es:"No importa", en:"It doesn't matter", alts:["It does not matter"], hint:"" },
//   { level:"A2", es:"Quizás después", en:"Maybe later", alts:["Perhaps later"], hint:"" },
//   { level:"A2", es:"¿Qué estás haciendo?", en:"What are you doing?", alts:[], hint:"Presente continuo en pregunta" },
//   { level:"A2", es:"Estoy viendo la tele", en:"I'm watching TV", alts:["I am watching TV"], hint:"watch para tele/películas" },
//   { level:"A2", es:"Fui a la playa ayer", en:"I went to the beach yesterday", alts:[], hint:"Pasado simple de go" },
//   { level:"A2", es:"Te llamaré después", en:"I'll call you back", alts:["I will call you back"], hint:"call back = devolver llamada" },
//   { level:"A2", es:"¿Estás listo?", en:"Are you ready?", alts:[], hint:"" },
//   { level:"A2", es:"¡Apúrate!", en:"Hurry up!", alts:[], hint:"" },
//   { level:"A2", es:"Tómate tu tiempo", en:"Take your time", alts:[], hint:"Expresión idiomática" },
//   { level:"A2", es:"Tú decides", en:"It's up to you", alts:["It is up to you"], hint:"" },
//   { level:"A2", es:"Déjame pensar", en:"Let me think", alts:[], hint:"let + me + verbo base" },
//   { level:"A2", es:"Cambié de opinión", en:"I changed my mind", alts:["I've changed my mind"], hint:"change one's mind" },
//   { level:"A2", es:"Esa es una buena idea", en:"That's a good idea", alts:["That is a good idea"], hint:"" },
//   { level:"A2", es:"No tengo idea", en:"I have no idea", alts:["I've no idea"], hint:"" },
//   { level:"A2", es:"¿Me estás bromeando?", en:"Are you kidding me?", alts:["Are you joking?"], hint:"" },
//   { level:"A2", es:"Ya vuelvo", en:"I'll be right back", alts:["I'll be back"], hint:"right back = enseguida" },
//   { level:"A2", es:"Siéntete como en casa", en:"Make yourself at home", alts:[], hint:"Frase fija" },
//   { level:"A2", es:"Tengo prisa", en:"I'm in a hurry", alts:["I am in a hurry"], hint:"in a hurry, no 'with'" },
//   { level:"A2", es:"¡Cuidado!", en:"Watch out!", alts:["Look out!","Be careful!"], hint:"" },
//   { level:"A2", es:"Estoy en camino", en:"I'm on my way", alts:["I am on my way"], hint:"on my way" },
//   { level:"A2", es:"Cálmate", en:"Calm down", alts:["Take it easy"], hint:"" },

//   // ============ B1 ============
//   { level:"B1", es:"Debí haberte llamado", en:"I should have called you", alts:["I should've called you"], hint:"should + have + participio = arrepentimiento" },
//   { level:"B1", es:"Si yo fuera tú, aceptaría el trabajo", en:"If I were you, I'd take the job", alts:["If I were you, I would take the job"], hint:"Condicional 2: If + were + would" },
//   { level:"B1", es:"Ha pasado mucho tiempo", en:"It's been a long time", alts:["It has been a long time","Long time no see"], hint:"Present perfect impersonal" },
//   { level:"B1", es:"Estoy acostumbrado a levantarme temprano", en:"I'm used to waking up early", alts:["I am used to waking up early"], hint:"used to + verbo-ing (costumbre)" },
//   { level:"B1", es:"No soporto este clima", en:"I can't stand this weather", alts:["I cannot stand this weather"], hint:"can't stand = odiar" },
//   { level:"B1", es:"Espero verte", en:"I look forward to seeing you", alts:["I'm looking forward to seeing you"], hint:"look forward TO + verbo-ing" },
//   { level:"B1", es:"Eso no es lo que quise decir", en:"That's not what I meant", alts:["That is not what I meant"], hint:"mean → meant" },
//   { level:"B1", es:"No podría estar más de acuerdo", en:"I couldn't agree more", alts:["I could not agree more"], hint:"Doble negativo idiomático = total acuerdo" },
//   { level:"B1", es:"No es gran cosa", en:"It's not a big deal", alts:["It's no big deal"], hint:"" },
//   { level:"B1", es:"Vayamos al grano", en:"Let's get to the point", alts:["Let's cut to the chase"], hint:"Idiomático" },
//   { level:"B1", es:"Te debo una", en:"I owe you one", alts:[], hint:"owe = deber" },
//   { level:"B1", es:"Vale la pena intentarlo", en:"It's worth a try", alts:["It's worth trying"], hint:"worth + sustantivo o gerundio" },
//   { level:"B1", es:"Eso tiene sentido", en:"That makes sense", alts:["It makes sense"], hint:"make + sense, no 'have'" },
//   { level:"B1", es:"No tuve otra opción", en:"I had no choice", alts:["I didn't have a choice"], hint:"" },
//   { level:"B1", es:"Se me está acabando el tiempo", en:"I'm running out of time", alts:["I am running out of time"], hint:"run out OF" },
//   { level:"B1", es:"No puedo creerlo", en:"I can't believe it", alts:["I cannot believe it"], hint:"" },
//   { level:"B1", es:"Ya era hora", en:"It's about time", alts:["About time"], hint:"Idiomático" },
//   { level:"B1", es:"No tengo ganas de salir", en:"I don't feel like going out", alts:["I do not feel like going out"], hint:"feel like + verbo-ing" },
//   { level:"B1", es:"Tengo que admitir", en:"I have to admit", alts:["I must admit"], hint:"" },
//   { level:"B1", es:"Hasta donde sé", en:"As far as I know", alts:[], hint:"Frase fija" },
//   { level:"B1", es:"Es pan comido", en:"It's a piece of cake", alts:["It's easy"], hint:"Modismo: muy fácil" },
//   { level:"B1", es:"Estoy harto de esto", en:"I'm fed up with this", alts:["I am fed up with this","I'm sick of this"], hint:"fed up WITH" },
//   { level:"B1", es:"Más vale prevenir que lamentar", en:"Better safe than sorry", alts:[], hint:"Refrán fijo" },
//   { level:"B1", es:"Las cosas mejorarán", en:"Things will get better", alts:["Things are going to get better"], hint:"get + adjetivo = volverse" },
//   { level:"B1", es:"Se me cruzó por la mente", en:"It crossed my mind", alts:[], hint:"Idiomático" },
//   { level:"B1", es:"Tenía un presentimiento", en:"I had a feeling", alts:[], hint:"" },
//   { level:"B1", es:"No lo tomes personal", en:"Don't take it personally", alts:["Do not take it personally"], hint:"personally con -ly" },
//   { level:"B1", es:"Démoslo por terminado", en:"Let's call it a day", alts:[], hint:"Modismo" },
//   { level:"B1", es:"Te aviso luego", en:"I'll get back to you", alts:["I will get back to you"], hint:"get back to = retomar contacto" },
//   { level:"B1", es:"No es lo mío", en:"It's not my cup of tea", alts:["It's not my thing"], hint:"Modismo británico-americano" },
//   { level:"B1", es:"Hablando del rey de Roma", en:"Speak of the devil", alts:[], hint:"Modismo fijo" },
//   { level:"B1", es:"Me suena", en:"It rings a bell", alts:[], hint:"Modismo: me resulta familiar" },
//   { level:"B1", es:"Lo estoy reconsiderando", en:"I'm having second thoughts", alts:["I am having second thoughts"], hint:"" },
//   { level:"B1", es:"Es más fácil decirlo que hacerlo", en:"That's easier said than done", alts:[], hint:"" },
//   { level:"B1", es:"No me malinterpretes", en:"Don't get me wrong", alts:[], hint:"" },
//   { level:"B1", es:"Se me olvidó", en:"It slipped my mind", alts:["I forgot"], hint:"Modismo" },
//   { level:"B1", es:"Mantenme al tanto", en:"Keep me posted", alts:["Keep me updated"], hint:"" },
//   { level:"B1", es:"Ve al grano", en:"Cut to the chase", alts:[], hint:"" },
//   { level:"B1", es:"Cuesta un ojo de la cara", en:"It costs an arm and a leg", alts:[], hint:"Modismo: muy caro" },
//   { level:"B1", es:"Estoy en un aprieto", en:"I'm in a tough spot", alts:["I'm in trouble"], hint:"" },
// ].map((p, i) => ({ id: i + 1, ...p }));