// 222 verbos regulares más usados en inglés
// En los regulares: pasado = participio = base + -ed (con variantes)
export const REGULAR_VERBS = [
  ["walk","walked","caminar"],
  ["listen","listened","escuchar"],
  ["look","looked","mirar"],
  ["learn","learned","aprender"],
  ["love","loved","amar"],
  ["like","liked","gustar"],
  ["smile","smiled","sonreír"],
  ["laugh","laughed","reír"],
  ["cry","cried","llorar"],
  ["dance","danced","bailar"],
  ["play","played","jugar"],
  ["call","called","llamar"],
  ["talk","talked","hablar"],
  ["ask","asked","preguntar"],
  ["answer","answered","responder"],
  ["work","worked","trabajar"],
  ["study","studied","estudiar"],
  ["travel","traveled","viajar"],
  ["live","lived","vivir"],
  ["clean","cleaned","limpiar"],
  ["cook","cooked","cocinar"],
  ["open","opened","abrir"],
  ["close","closed","cerrar"],
  ["enter","entered","entrar"],
  ["receive","received","recibir"],
  ["help","helped","ayudar"],
  ["support","supported","apoyar"],
  ["start","started","empezar"],
  ["stop","stopped","detener"],
  ["finish","finished","terminar"],
  ["create","created","crear"],
  ["destroy","destroyed","destruir"],
  ["change","changed","cambiar"],
  ["carry","carried","llevar"],
  ["rain","rained","llover"],
  ["drop","dropped","dejar caer"],
  ["knock","knocked","golpear"],
  ["wash","washed","lavar"],
  ["dress","dressed","vestirse"],
  ["pack","packed","empacar"],
  ["save","saved","ahorrar"],
  ["fail","failed","fallar"],
  ["achieve","achieved","lograr"],
  ["decide","decided","decidir"],
  ["thank","thanked","agradecer"],
  ["celebrate","celebrated","celebrar"],
  ["shop","shopped","comprar"],
  ["capture","captured","capturar"],
  ["repair","repaired","reparar"],
  ["solve","solved","resolver"],
  ["try","tried","intentar"],
  ["wait","waited","esperar"],
  ["improve","improved","mejorar"],
  ["increase","increased","aumentar"],
  ["explore","explored","explorar"]
  // ["accept","accepted","aceptar"],
  // ["add","added","agregar / sumar"],
  // ["admire","admired","admirar"],
  // ["admit","admitted","admitir"],
  // ["advise","advised","aconsejar"],
  // ["affect","affected","afectar"],
  // ["agree","agreed","estar de acuerdo"],
  // ["allow","allowed","permitir"],
  // ["answer","answered","responder"],
  // ["appear","appeared","aparecer"],
  // ["apply","applied","aplicar / postularse"],
  // ["argue","argued","discutir"],
  // ["arrange","arranged","organizar"],
  // ["arrive","arrived","llegar"],
  // ["ask","asked","preguntar"],
  // ["attach","attached","adjuntar"],
  // ["attack","attacked","atacar"],
  // ["attempt","attempted","intentar"],
  // ["attend","attended","asistir"],
  // ["avoid","avoided","evitar"],
  // ["behave","behaved","comportarse"],
  // ["believe","believed","creer"],
  // ["belong","belonged","pertenecer"],
  // ["blame","blamed","culpar"],
  // ["borrow","borrowed","pedir prestado"],
  // ["bother","bothered","molestar"],
  // ["breathe","breathed","respirar"],
  // ["call","called","llamar"],
  // ["calm","calmed","calmar"],
  // ["cancel","canceled","cancelar"],
  // ["care","cared","importar"],
  // ["carry","carried","llevar"],
  // ["cause","caused","causar"],
  // ["change","changed","cambiar"],
  // ["charge","charged","cobrar"],
  // ["chat","chatted","charlar"],
  // ["check","checked","revisar"],
  // ["clean","cleaned","limpiar"],
  // ["close","closed","cerrar"],
  // ["collect","collected","coleccionar"],
  // ["compare","compared","comparar"],
  // ["compete","competed","competir"],
  // ["complain","complained","quejarse"],
  // ["complete","completed","completar"],
  // ["concentrate","concentrated","concentrarse"],
  // ["confess","confessed","confesar"],
  // ["confuse","confused","confundir"],
  // ["connect","connected","conectar"],
  // ["consider","considered","considerar"],
  // ["contain","contained","contener"],
  // ["continue","continued","continuar"],
  // ["control","controlled","controlar"],
  // ["cook","cooked","cocinar"],
  // ["copy","copied","copiar"],
  // ["correct","corrected","corregir"],
  // ["count","counted","contar"],
  // ["cover","covered","cubrir"],
  // ["cross","crossed","cruzar"],
  // ["cry","cried","llorar"],
  // ["dance","danced","bailar"],
  // ["decide","decided","decidir"],
  // ["deliver","delivered","entregar"],
  // ["depend","depended","depender"],
  // ["describe","described","describir"],
  // ["destroy","destroyed","destruir"],
  // ["die","died","morir"],
  // ["disagree","disagreed","estar en desacuerdo"],
  // ["disappear","disappeared","desaparecer"],
  // ["discover","discovered","descubrir"],
  // ["discuss","discussed","debatir"],
  // ["divide","divided","dividir"],
  // ["download","downloaded","descargar"],
  // ["dress","dressed","vestirse"],
  // ["drop","dropped","dejar caer"],
  // ["dry","dried","secar"],
  // ["earn","earned","ganar (dinero)"],
  // ["educate","educated","educar"],
  // ["employ","employed","emplear"],
  // ["encourage","encouraged","animar"],
  // ["end","ended","terminar"],
  // ["enjoy","enjoyed","disfrutar"],
  // ["enter","entered","entrar"],
  // ["escape","escaped","escapar"],
  // ["examine","examined","examinar"],
  // ["exchange","exchanged","intercambiar"],
  // ["excuse","excused","disculpar"],
  // ["exist","existed","existir"],
  // ["expect","expected","esperar (suponer)"],
  // ["explain","explained","explicar"],
  // ["explore","explored","explorar"],
  // ["express","expressed","expresar"],
  // ["fail","failed","fallar"],
  // ["fear","feared","temer"],
  // ["fill","filled","llenar"],
  // ["finish","finished","terminar"],
  // ["fix","fixed","arreglar"],
  // ["follow","followed","seguir"],
  // ["force","forced","forzar"],
  // ["gather","gathered","reunir"],
  // ["greet","greeted","saludar"],
  // ["guess","guessed","adivinar"],
  // ["happen","happened","suceder"],
  // ["harm","harmed","dañar"],
  // ["hate","hated","odiar"],
  // ["help","helped","ayudar"],
  // ["hope","hoped","esperar"],
  // ["hug","hugged","abrazar"],
  // ["identify","identified","identificar"],
  // ["ignore","ignored","ignorar"],
  // ["imagine","imagined","imaginar"],
  // ["improve","improved","mejorar"],
  // ["include","included","incluir"],
  // ["increase","increased","aumentar"],
  // ["influence","influenced","influenciar"],
  // ["inform","informed","informar"],
  // ["injure","injured","herir"],
  // ["insist","insisted","insistir"],
  // ["install","installed","instalar"],
  // ["interrupt","interrupted","interrumpir"],
  // ["introduce","introduced","presentar"],
  // ["invent","invented","inventar"],
  // ["invite","invited","invitar"],
  // ["join","joined","unirse"],
  // ["judge","judged","juzgar"],
  // ["jump","jumped","saltar"],
  // ["kill","killed","matar"],
  // ["land","landed","aterrizar"],
  // ["last","lasted","durar"],
  // ["laugh","laughed","reír"],
  // ["like","liked","gustar"],
  // ["listen","listened","escuchar"],
  // ["live","lived","vivir"],
  // ["look","looked","mirar"],
  // ["love","loved","amar"],
  // ["manage","managed","gestionar"],
  // ["marry","married","casarse"],
  // ["matter","mattered","importar"],
  // ["measure","measured","medir"],
  // ["mention","mentioned","mencionar"],
  // ["miss","missed","extrañar"],
  // ["mix","mixed","mezclar"],
  // ["move","moved","mover"],
  // ["need","needed","necesitar"],
  // ["notice","noticed","notar"],
  // ["offer","offered","ofrecer"],
  // ["open","opened","abrir"],
  // ["order","ordered","pedir"],
  // ["own","owned","poseer"],
  // ["pack","packed","empacar"],
  // ["paint","painted","pintar"],
  // ["park","parked","estacionar"],
  // ["pass","passed","pasar"],
  // ["pick","picked","elegir"],
  // ["plan","planned","planear"],
  // ["plant","planted","plantar"],
  // ["play","played","jugar"],
  // ["point","pointed","señalar"],
  // ["pour","poured","verter"],
  // ["practice","practiced","practicar"],
  // ["prefer","preferred","preferir"],
  // ["prepare","prepared","preparar"],
  // ["present","presented","presentar"],
  // ["press","pressed","presionar"],
  // ["pretend","pretended","fingir"],
  // ["prevent","prevented","prevenir"],
  // ["print","printed","imprimir"],
  // ["promise","promised","prometer"],
  // ["pronounce","pronounced","pronunciar"],
  // ["protect","protected","proteger"],
  // ["provide","provided","proveer"],
  // ["pull","pulled","jalar"],
  // ["push","pushed","empujar"],
  // ["raise","raised","levantar"],
  // ["reach","reached","alcanzar"],
  // ["realize","realized","darse cuenta"],
  // ["receive","received","recibir"],
  // ["recognize","recognized","reconocer"],
  // ["recommend","recommended","recomendar"],
  // ["record","recorded","grabar"],
  // ["reduce","reduced","reducir"],
  // ["refuse","refused","rechazar"],
  // ["relax","relaxed","relajarse"],
  // ["remember","remembered","recordar"],
  // ["remove","removed","quitar"],
  // ["rent","rented","alquilar"],
  // ["repair","repaired","reparar"],
  // ["repeat","repeated","repetir"],
  // ["reply","replied","responder"],
  // ["report","reported","reportar"],
  // ["request","requested","solicitar"],
  // ["rescue","rescued","rescatar"],
  // ["respect","respected","respetar"],
  // ["rest","rested","descansar"],
  // ["return","returned","regresar"],
  // ["save","saved","ahorrar"],
  // ["shout","shouted","gritar"],
  // ["smile","smiled","sonreír"],
  // ["start","started","empezar"],
  // ["stop","stopped","detener"],
  // ["study","studied","estudiar"],
  // ["talk","talked","hablar"],
  // ["travel","traveled","viajar"],
  // ["try","tried","intentar"],
  // ["use","used","usar"],
  // ["visit","visited","visitar"],
  // ["wait","waited","esperar"],
  // ["walk","walked","caminar"],
  // ["want","wanted","querer"],
  // ["wash","washed","lavar"],
  // ["watch","watched","ver"],
  // ["work","worked","trabajar"],
  // ["worry","worried","preocuparse"]
].map(([base, past, es], i) => ({
  id: 1000 + i + 1,
  base,
  past,
  pp: past,          // en regulares, participio = pasado
  es,
  type: "regular",
}));