// 222 verbos regulares más usados en inglés
// En los regulares: pasado = participio = base + -ed (con variantes)
export const REGULAR_VERBS = [
  ["accept","accepted","aceptar"],
  ["add","added","agregar / sumar"],
  ["admire","admired","admirar"],
  ["admit","admitted","admitir"],
  ["advise","advised","aconsejar"],
  ["affect","affected","afectar"],
  ["agree","agreed","estar de acuerdo"],
  ["allow","allowed","permitir"],
  ["answer","answered","responder"],
  ["appear","appeared","aparecer"],
  ["apply","applied","aplicar / postularse"],
  ["argue","argued","discutir"],
  ["arrange","arranged","arreglar / organizar"],
  ["arrest","arrested","arrestar"],
  ["arrive","arrived","llegar"],
  ["ask","asked","preguntar"],
  ["attach","attached","adjuntar"],
  ["attack","attacked","atacar"],
  ["attempt","attempted","intentar"],
  ["attend","attended","asistir"],
  ["avoid","avoided","evitar"],
  ["bake","baked","hornear"],
  ["bathe","bathed","bañarse"],
  ["beg","begged","rogar"],
  ["behave","behaved","comportarse"],
  ["believe","believed","creer"],
  ["belong","belonged","pertenecer"],
  ["blame","blamed","culpar"],
  ["boil","boiled","hervir"],
  ["borrow","borrowed","pedir prestado"],
  ["bother","bothered","molestar"],
  ["breathe","breathed","respirar"],
  ["brush","brushed","cepillar"],
  ["call","called","llamar"],
  ["calm","calmed","calmar"],
  ["cancel","canceled","cancelar"],
  ["care","cared","cuidar / importar"],
  ["carry","carried","llevar / cargar"],
  ["cause","caused","causar"],
  ["change","changed","cambiar"],
  ["charge","charged","cobrar / cargar"],
  ["chase","chased","perseguir"],
  ["chat","chatted","charlar"],
  ["check","checked","revisar"],
  ["cheer","cheered","animar / aplaudir"],
  ["chew","chewed","masticar"],
  ["clap","clapped","aplaudir"],
  ["clean","cleaned","limpiar"],
  ["climb","climbed","escalar"],
  ["close","closed","cerrar"],
  ["collect","collected","coleccionar"],
  ["comb","combed","peinar"],
  ["command","commanded","ordenar / mandar"],
  ["compare","compared","comparar"],
  ["compete","competed","competir"],
  ["complain","complained","quejarse"],
  ["complete","completed","completar"],
  ["concentrate","concentrated","concentrarse"],
  ["confess","confessed","confesar"],
  ["confuse","confused","confundir"],
  ["connect","connected","conectar"],
  ["consider","considered","considerar"],
  ["contain","contained","contener"],
  ["continue","continued","continuar"],
  ["control","controlled","controlar"],
  ["cook","cooked","cocinar"],
  ["copy","copied","copiar"],
  ["correct","corrected","corregir"],
  ["cough","coughed","toser"],
  ["count","counted","contar (números)"],
  ["cover","covered","cubrir"],
  ["crash","crashed","estrellar"],
  ["cross","crossed","cruzar"],
  ["cry","cried","llorar"],
  ["cycle","cycled","andar en bicicleta"],
  ["dance","danced","bailar"],
  ["decide","decided","decidir"],
  ["deliver","delivered","entregar"],
  ["depend","depended","depender"],
  ["describe","described","describir"],
  ["destroy","destroyed","destruir"],
  ["die","died","morir"],
  ["disagree","disagreed","estar en desacuerdo"],
  ["disappear","disappeared","desaparecer"],
  ["discover","discovered","descubrir"],
  ["discuss","discussed","debatir"],
  ["divide","divided","dividir"],
  ["download","downloaded","descargar"],
  ["drag","dragged","arrastrar"],
  ["dress","dressed","vestirse"],
  ["drop","dropped","dejar caer"],
  ["dry","dried","secar"],
  ["earn","earned","ganar (dinero)"],
  ["educate","educated","educar"],
  ["embarrass","embarrassed","avergonzar"],
  ["employ","employed","emplear"],
  ["empty","emptied","vaciar"],
  ["encourage","encouraged","animar"],
  ["end","ended","terminar"],
  ["enjoy","enjoyed","disfrutar"],
  ["enter","entered","entrar"],
  ["escape","escaped","escapar"],
  ["examine","examined","examinar"],
  ["exchange","exchanged","intercambiar"],
  ["excuse","excused","disculpar"],
  ["exist","existed","existir"],
  ["expect","expected","esperar (suponer)"],
  ["explain","explained","explicar"],
  ["explore","explored","explorar"],
  ["express","expressed","expresar"],
  ["fail","failed","fallar / reprobar"],
  ["fasten","fastened","abrochar"],
  ["fear","feared","temer"],
  ["fetch","fetched","ir a buscar"],
  ["fill","filled","llenar"],
  ["finish","finished","terminar"],
  ["fish","fished","pescar"],
  ["fix","fixed","arreglar"],
  ["float","floated","flotar"],
  ["fold","folded","doblar"],
  ["follow","followed","seguir"],
  ["fool","fooled","engañar"],
  ["force","forced","forzar"],
  ["frighten","frightened","asustar"],
  ["fry","fried","freír"],
  ["gather","gathered","reunir"],
  ["glue","glued","pegar (pegamento)"],
  ["greet","greeted","saludar"],
  ["guess","guessed","adivinar"],
  ["happen","happened","suceder"],
  ["harm","harmed","dañar"],
  ["hate","hated","odiar"],
  ["heat","heated","calentar"],
  ["help","helped","ayudar"],
  ["hope","hoped","esperar (desear)"],
  ["hug","hugged","abrazar"],
  ["hunt","hunted","cazar"],
  ["hurry","hurried","apurarse"],
  ["identify","identified","identificar"],
  ["ignore","ignored","ignorar"],
  ["imagine","imagined","imaginar"],
  ["improve","improved","mejorar"],
  ["include","included","incluir"],
  ["increase","increased","aumentar"],
  ["influence","influenced","influenciar"],
  ["inform","informed","informar"],
  ["injure","injured","herir"],
  ["insist","insisted","insistir"],
  ["install","installed","instalar"],
  ["interrupt","interrupted","interrumpir"],
  ["introduce","introduced","presentar (a alguien)"],
  ["invent","invented","inventar"],
  ["invite","invited","invitar"],
  ["iron","ironed","planchar"],
  ["jog","jogged","trotar"],
  ["join","joined","unirse"],
  ["joke","joked","bromear"],
  ["judge","judged","juzgar"],
  ["jump","jumped","saltar"],
  ["kick","kicked","patear"],
  ["kill","killed","matar"],
  ["kiss","kissed","besar"],
  ["knock","knocked","tocar (puerta)"],
  ["land","landed","aterrizar"],
  ["last","lasted","durar"],
  ["laugh","laughed","reír"],
  ["like","liked","gustar"],
  ["listen","listened","escuchar"],
  ["live","lived","vivir"],
  ["lock","locked","cerrar con llave"],
  ["look","looked","mirar"],
  ["love","loved","amar"],
  ["mail","mailed","enviar por correo"],
  ["manage","managed","gestionar"],
  ["march","marched","marchar"],
  ["mark","marked","marcar"],
  ["marry","married","casarse"],
  ["match","matched","emparejar"],
  ["matter","mattered","importar"],
  ["measure","measured","medir"],
  ["melt","melted","derretir"],
  ["mention","mentioned","mencionar"],
  ["miss","missed","extrañar / perder"],
  ["mix","mixed","mezclar"],
  ["move","moved","mover"],
  ["need","needed","necesitar"],
  ["notice","noticed","notar"],
  ["obey","obeyed","obedecer"],
  ["offer","offered","ofrecer"],
  ["open","opened","abrir"],
  ["order","ordered","ordenar / pedir"],
  ["own","owned","poseer"],
  ["pack","packed","empacar"],
  ["paint","painted","pintar"],
  ["park","parked","estacionar"],
  ["pass","passed","pasar / aprobar"],
  ["pause","paused","pausar"],
  ["pick","picked","recoger / elegir"],
  ["plan","planned","planear"],
  ["plant","planted","plantar"],
  ["play","played","jugar"],
  ["please","pleased","complacer"],
  ["point","pointed","señalar"],
  ["polish","polished","pulir"],
  ["pour","poured","verter"],
  ["practice","practiced","practicar"],
  ["pray","prayed","rezar"],
  ["prefer","preferred","preferir"],
  ["prepare","prepared","preparar"],
  ["present","presented","presentar"],
  ["press","pressed","presionar"],
  ["pretend","pretended","fingir"],
  ["prevent","prevented","prevenir"],
  ["print","printed","imprimir"],
  ["promise","promised","prometer"],
  ["pronounce","pronounced","pronunciar"],
  ["protect","protected","proteger"],
  ["provide","provided","proveer"],
  ["pull","pulled","jalar"],
  ["punch","punched","golpear (puño)"],
  ["punish","punished","castigar"],
  ["push","pushed","empujar"],
  ["raise","raised","levantar / criar"],
  ["reach","reached","alcanzar"],
  ["realize","realized","darse cuenta"],
  ["receive","received","recibir"],
  ["recognize","recognized","reconocer"],
  ["recommend","recommended","recomendar"],
  ["record","recorded","grabar"],
  ["reduce","reduced","reducir"],
  ["refuse","refused","rechazar"],
  ["relax","relaxed","relajarse"],
  ["remember","remembered","recordar"],
  ["remove","removed","quitar"],
  ["rent","rented","alquilar"],
  ["repair","repaired","reparar"],
  ["repeat","repeated","repetir"],
  ["reply","replied","responder"],
  ["report","reported","reportar"],
  ["request","requested","solicitar"],
  ["rescue","rescued","rescatar"],
  ["respect","respected","respetar"],
  ["rest","rested","descansar"],
  ["return","returned","regresar / devolver"],
  ["save","saved","salvar / ahorrar"],
  ["shout","shouted","gritar"],
  ["smile","smiled","sonreír"],
  ["start","started","empezar"],
  ["stop","stopped","detener"],
  ["study","studied","estudiar"],
  ["talk","talked","hablar"],
  ["travel","traveled","viajar"],
  ["try","tried","intentar"],
  ["use","used","usar"],
  ["visit","visited","visitar"],
  ["wait","waited","esperar"],
  ["walk","walked","caminar"],
  ["want","wanted","querer"],
  ["wash","washed","lavar"],
  ["watch","watched","ver / observar"],
  ["work","worked","trabajar"],
  ["worry","worried","preocuparse"],
].map(([base, past, es], i) => ({
  id: 1000 + i + 1,
  base,
  past,
  pp: past,          // en regulares, participio = pasado
  es,
  type: "regular",
}));