// 220 verbos irregulares más usados en inglés
export const VERBS = [
  ["be","was/were","been","ser / estar"],
  ["become","became","become","convertirse / llegar a ser"],
  ["begin","began","begun","empezar"],
  ["bend","bent","bent","doblar"],
  ["bet","bet","bet","apostar"],
  ["bind","bound","bound","atar"],
  ["bite","bit","bitten","morder"],
  ["bleed","bled","bled","sangrar"],
  ["blow","blew","blown","soplar"],
  ["break","broke","broken","romper"],
  ["breed","bred","bred","criar"],
  ["bring","brought","brought","traer"],
  ["broadcast","broadcast","broadcast","transmitir"],
  ["build","built","built","construir"],
  ["burn","burned","burned","quemar"],
  ["burst","burst","burst","estallar"],
  ["buy","bought","bought","comprar"],
  ["cast","cast","cast","lanzar / arrojar"],
  ["catch","caught","caught","atrapar"],
  ["choose","chose","chosen","elegir"],
  ["cling","clung","clung","aferrarse"],
  ["come","came","come","venir"],
  ["cost","cost","cost","costar"],
  ["creep","crept","crept","arrastrarse"],
  ["cut","cut","cut","cortar"],
  ["deal","dealt","dealt","tratar / negociar"],
  ["dig","dug","dug","cavar"],
  ["dive","dove","dived","bucear / zambullirse"],
  ["do","did","done","hacer"],
  ["draw","drew","drawn","dibujar"],
  ["dream","dreamed","dreamed","soñar"],
  ["drink","drank","drunk","beber"],
  ["drive","drove","driven","conducir"],
  ["eat","ate","eaten","comer"],
  ["fall","fell","fallen","caer"],
  ["feed","fed","fed","alimentar"],
  ["feel","felt","felt","sentir"],
  ["fight","fought","fought","pelear"],
  ["find","found","found","encontrar"],
  ["fit","fit","fit","encajar / quedar bien"],
  ["flee","fled","fled","huir"],
  ["fling","flung","flung","arrojar"],
  ["fly","flew","flown","volar"],
  ["forbid","forbade","forbidden","prohibir"],
  ["forecast","forecast","forecast","pronosticar"],
  ["forget","forgot","forgotten","olvidar"],
  ["forgive","forgave","forgiven","perdonar"],
  ["freeze","froze","frozen","congelar"],
  ["get","got","gotten","obtener"],
  ["give","gave","given","dar"],
  ["go","went","gone","ir"],
  ["grind","ground","ground","moler"],
  ["grow","grew","grown","crecer"],
  ["hang","hung","hung","colgar"],
  ["have","had","had","tener / haber"],
  ["hear","heard","heard","oír / escuchar"],
  ["hide","hid","hidden","esconder"],
  ["hit","hit","hit","golpear"],
  ["hold","held","held","sostener"],
  ["hurt","hurt","hurt","lastimar / doler"],
  ["keep","kept","kept","mantener / conservar"],
  ["kneel","knelt","knelt","arrodillarse"],
  ["knit","knit","knit","tejer"],
  ["know","knew","known","saber / conocer"],
  ["lay","laid","laid","poner / colocar"],
  ["lead","led","led","liderar / guiar"],
  ["lean","leaned","leaned","apoyarse / inclinarse"],
  ["leap","leaped","leaped","saltar"],
  ["learn","learned","learned","aprender"],
  ["leave","left","left","dejar / salir"],
  ["lend","lent","lent","prestar"],
  ["let","let","let","dejar / permitir"],
  ["lie","lay","lain","acostarse / yacer"],
  ["light","lit","lit","encender / iluminar"],
  ["lose","lost","lost","perder"],
  ["make","made","made","hacer / fabricar"],
  ["mean","meant","meant","significar"],
  ["meet","met","met","conocer / encontrarse"],
  ["mistake","mistook","mistaken","equivocarse"],
  ["mow","mowed","mown","segar / cortar césped"],
  ["overcome","overcame","overcome","superar"],
  ["overtake","overtook","overtaken","rebasar / adelantar"],
  ["pay","paid","paid","pagar"],
  ["plead","pled","pled","suplicar"],
  ["prove","proved","proven","probar / demostrar"],
  ["put","put","put","poner"],
  ["quit","quit","quit","renunciar / dejar"],
  ["read","read","read","leer"],
  ["rid","rid","rid","librar / deshacerse"],
  ["ride","rode","ridden","montar"],
  ["ring","rang","rung","sonar / llamar"],
  ["rise","rose","risen","elevarse / levantarse"],
  ["run","ran","run","correr"],
  ["saw","sawed","sawn","serrar"],
  ["say","said","said","decir"],
  ["see","saw","seen","ver"],
  ["seek","sought","sought","buscar"],
  ["sell","sold","sold","vender"],
  ["send","sent","sent","enviar"],
  ["set","set","set","establecer / colocar"],
  ["sew","sewed","sewn","coser"],
  ["shake","shook","shaken","sacudir"],
  ["shave","shaved","shaven","afeitar"],
  ["shear","sheared","shorn","esquilar"],
  ["shed","shed","shed","derramar / mudar"],
  ["shine","shone","shone","brillar"],
  ["shoot","shot","shot","disparar"],
  ["show","showed","shown","mostrar"],
  ["shrink","shrank","shrunk","encoger"],
  ["shut","shut","shut","cerrar"],
  ["sing","sang","sung","cantar"],
  ["sink","sank","sunk","hundir"],
  ["sit","sat","sat","sentarse"],
  ["sleep","slept","slept","dormir"],
  ["slide","slid","slid","deslizar"],
  ["sling","slung","slung","lanzar / colgar"],
  ["slit","slit","slit","rajar / cortar"],
  ["smell","smelled","smelled","oler"],
  ["sow","sowed","sown","sembrar"],
  ["speak","spoke","spoken","hablar"],
  ["speed","sped","sped","acelerar"],
  ["spell","spelled","spelled","deletrear"],
  ["spend","spent","spent","gastar / pasar tiempo"],
  ["spill","spilled","spilled","derramar"],
  ["spin","spun","spun","girar"],
  ["spit","spat","spat","escupir"],
  ["split","split","split","dividir / partir"],
  ["spoil","spoiled","spoiled","estropear / mimar"],
  ["spread","spread","spread","extender / esparcir"],
  ["spring","sprang","sprung","saltar / brincar"],
  ["stand","stood","stood","estar de pie"],
  ["steal","stole","stolen","robar"],
  ["stick","stuck","stuck","pegar / clavar"],
  ["sting","stung","stung","picar"],
  ["stink","stank","stunk","apestar"],
  ["stride","strode","stridden","dar zancadas"],
  ["strike","struck","struck","golpear / huelga"],
  ["string","strung","strung","encordar"],
  ["strive","strove","striven","esforzarse"],
  ["swear","swore","sworn","jurar"],
  ["sweep","swept","swept","barrer"],
  ["swell","swelled","swollen","hincharse"],
  ["swim","swam","swum","nadar"],
  ["swing","swung","swung","balancearse"],
  ["take","took","taken","tomar / llevar"],
  ["teach","taught","taught","enseñar"],
  ["tear","tore","torn","rasgar"],
  ["tell","told","told","decir / contar"],
  ["think","thought","thought","pensar"],
  ["throw","threw","thrown","lanzar"],
  ["thrust","thrust","thrust","empujar"],
  ["tread","trod","trodden","pisar"],
  ["understand","understood","understood","entender"],
  ["undertake","undertook","undertaken","emprender"],
  ["upset","upset","upset","molestar / disgustar"],
  ["wake","woke","woken","despertar"],
  ["wear","wore","worn","llevar puesto / vestir"],
  ["weave","wove","woven","tejer"],
  ["weep","wept","wept","llorar"],
  ["wet","wet","wet","mojar"],
  ["win","won","won","ganar"],
  ["wind","wound","wound","enrollar"],
  ["withdraw","withdrew","withdrawn","retirar"],
  ["wring","wrung","wrung","retorcer"],
  ["write","wrote","written","escribir"],
  ["arise","arose","arisen","surgir"],
  ["awake","awoke","awoken","despertar"],
  ["babysit","babysat","babysat","cuidar niños"],
  ["beat","beat","beaten","golpear / vencer"],
  ["behold","beheld","beheld","contemplar"],
  ["bid","bid","bid","ofertar / pujar"],
  ["dwell","dwelt","dwelt","habitar / morar"],
  ["forsake","forsook","forsaken","abandonar"],
  ["handwrite","handwrote","handwritten","escribir a mano"],
  ["inlay","inlaid","inlaid","incrustar"],
  ["interbreed","interbred","interbred","cruzar (especies)"],
  ["lipread","lipread","lipread","leer los labios"],
  ["miscast","miscast","miscast","asignar mal un papel"],
  ["misdeal","misdealt","misdealt","repartir mal"],
  ["mishear","misheard","misheard","oír mal"],
  ["mislead","misled","misled","engañar"],
  ["misread","misread","misread","leer mal"],
  ["misspell","misspelled","misspelled","escribir mal"],
  ["misunderstand","misunderstood","misunderstood","malentender"],
  ["offset","offset","offset","compensar"],
  ["outbid","outbid","outbid","superar en oferta"],
  ["outdo","outdid","outdone","superar"],
  ["outgrow","outgrew","outgrown","dejar de caber en"],
  ["outrun","outran","outrun","correr más rápido que"],
  ["outsell","outsold","outsold","vender más que"],
  ["partake","partook","partaken","participar"],
  ["preset","preset","preset","preestablecer"],
  ["proofread","proofread","proofread","corregir pruebas"],
  ["recast","recast","recast","reformular"],
  ["redo","redid","redone","rehacer"],
  ["remake","remade","remade","volver a hacer"],
  ["repay","repaid","repaid","reembolsar"],
  ["rerun","reran","rerun","volver a ejecutar"],
  ["resell","resold","resold","revender"],
  ["reset","reset","reset","restablecer"],
  ["retake","retook","retaken","retomar"],
  ["retell","retold","retold","volver a contar"],
  ["rewind","rewound","rewound","rebobinar"],
  ["rewrite","rewrote","rewritten","reescribir"],
  ["unbend","unbent","unbent","enderezar"],
  ["undergo","underwent","undergone","someterse a"],
  ["unwind","unwound","unwound","desenrollar / relajarse"],
  ["uphold","upheld","upheld","mantener / sostener"],
  ["waylay","waylaid","waylaid","emboscar"],
  ["foresee","foresaw","foreseen","prever"],
  ["foretell","foretold","foretold","predecir"],
  ["overhear","overheard","overheard","oír por casualidad"],
  ["overpay","overpaid","overpaid","pagar de más"],
  ["overrun","overran","overrun","invadir"],
  ["oversee","oversaw","overseen","supervisar"],
  ["oversleep","overslept","overslept","quedarse dormido"],
  ["rebuild","rebuilt","rebuilt","reconstruir"],
  ["spit","spit","spit","escupir (variante)"],
  ["spotlight","spotlit","spotlit","iluminar"],
  ["sublet","sublet","sublet","subarrendar"],
  ["typeset","typeset","typeset","componer (imprenta)"],
  ["undo","undid","undone","deshacer"],
  ["withhold","withheld","withheld","retener"],
  ["withstand","withstood","withstood","resistir"],
].map(([base, past, pp, es], i) => ({
  id: i + 1,
  base,
  past,
  pp,
  es,
  type: "irregular",
}));