// 220 verbos irregulares más usados en inglés
export const VERBS = [
["be", "was / were", "been", "ser / estar"],
  ["have", "had", "had", "tener / haber"],
  ["do", "did", "done", "hacer / realizar"],
  ["get", "got", "gotten", "conseguir / obtener / llegar / entender"],
  ["go", "went", "gone", "ir"],
  ["come", "came", "come", "venir / llegar"],
  ["take", "took", "taken", "tomar / llevar / tardar"],
  ["make", "made", "made", "hacer / fabricar / crear"],
  ["put", "put", "put", "poner / colocar"],
  ["give", "gave", "given", "dar / entregar"],
  ["bring", "brought", "brought", "traer / llevar"],
  ["run", "ran", "run", "correr / ejecutar / administrar"],
  ["keep", "kept", "kept", "mantener / guardar / continuar"],
  ["leave", "left", "left", "dejar / salir / irse"],
  ["know", "knew", "known", "saber / conocer"],
  ["think", "thought", "thought", "pensar / creer"],
  ["see", "saw", "seen", "ver"],
  ["look", "looked", "looked", "mirar / parecer"],
  ["feel", "felt", "felt", "sentir / sentirse"],
  ["find", "found", "found", "encontrar / hallar"],
  ["understand", "understood", "understood", "entender / comprender"],
  ["say", "said", "said", "decir"],
  ["tell", "told", "told", "decir / contar / informar"],
  ["mean", "meant", "meant", "significar / querer decir"],
  ["want", "wanted", "wanted", "querer / desear"],
  ["need", "needed", "needed", "necesitar"],
  ["try", "tried", "tried", "intentar / probar"],
  ["let", "let", "let", "permitir / dejar"],
  ["use", "used", "used", "usar / utilizar"],
  ["call", "called", "called", "llamar"]
  ["bring","brought","brought","traer / llevar"],

// ["arise","arose","arisen","surgir / levantarse"],
// ["awake","awoke","awoken","despertarse"],
// ["be","was were","been","ser / estar"],
// ["bear","bore","borne born","soportar / dar a luz"],
// ["beat","beat","beaten","golpear"],
// ["become","became","become","llegar a ser"],
// ["begin","began","begun","empezar"],
// ["bend","bent","bent","doblar"],
// ["bet","bet","bet","apostar"],
// ["bind","bound","bound","atar / encuadernar"],
// ["bid","bid","bid","pujar"],
// ["bite","bit","bitten","morder"],
// ["bleed","bled","bled","sangrar"],
// ["blow","blew","blown","soplar"],
// ["break","broke","broken","romper"],
// ["breed","bred","bred","criar"],
// ["bring","brought","brought","traer / llevar"],
// ["broadcast","broadcast","broadcast","radiar"],
// ["build","built","built","edificar"],
// ["burn","burned","burnt/burned","quemar"],
// ["burst","burst","burst","reventar"],
// ["buy","bought","bought","comprar"],
// ["cast","cast","cast","arrojar"],
// ["catch","caught","caught","coger"],
// ["come","came","come","venir"],
// ["cost","cost","cost","costar"],
// ["cut","cut","cut","cortar"],
// ["choose","chose","chosen","elegir"],
// ["cling","clung","clung","agarrarse"],
// ["creep","crept","crept","arrastrarse"],
// ["deal","dealt","dealt","tratar"],
// ["dig","dug","dug","cavar"],
// ["do","did","done","hacer"],
// ["draw","drew","drawn","dibujar"],
// ["dream","dreamed","dreamed","soñar"],
// ["drink","drank","drunk","beber"],
// ["drive","drove","driven","conducir"],
// ["eat","ate","eaten","comer"],
// ["fall","fell","fallen","caer"],
// ["feed","fed","fed","alimentar"],
// ["feel","felt","felt","sentir"],
// ["fight","fought","fought","luchar"],
// ["find","found","found","encontrar"],
// ["flee","fled","fled","huir"],
// ["fly","flew","flown","volar"],
// ["forbid","forbade","forbidden","prohibir"],
// ["forget","forgot","forgotten","olvidar"],
// ["forgive","forgave","forgiven","perdonar"],
// ["freeze","froze","frozen","helar"]
  /* ["be","was/were","been","ser / estar"],
  ["have","had","had","tener / haber"],
  ["do","did","done","hacer"],
  ["say","said","said","decir"],
  ["go","went","gone","ir"],
  ["get","got","gotten","obtener"],
  ["make","made","made","hacer / fabricar"],
  ["know","knew","known","saber / conocer"],
  ["think","thought","thought","pensar"],
  ["take","took","taken","tomar / llevar"],
  ["see","saw","seen","ver"],
  ["come","came","come","venir"],
  ["give","gave","given","dar"],
  ["find","found","found","encontrar"],
  ["tell","told","told","decir / contar"],
  ["become","became","become","convertirse / llegar a ser"],
  ["show","showed","shown","mostrar"],
  ["leave","left","left","dejar / salir"],
  ["feel","felt","felt","sentir"],
  ["put","put","put","poner"],
  ["bring","brought","brought","traer"],
  ["begin","began","begun","empezar"],
  ["keep","kept","kept","mantener / conservar"],
  ["hold","held","held","sostener"],
  ["write","wrote","written","escribir"],
  ["stand","stood","stood","estar de pie"],
  ["hear","heard","heard","oír / escuchar"],
  ["let","let","let","dejar / permitir"],
  ["mean","meant","meant","significar"],
  ["set","set","set","establecer / colocar"],
  ["meet","met","met","conocer / encontrarse"],
  ["run","ran","run","correr"],
  ["pay","paid","paid","pagar"],
  ["sit","sat","sat","sentarse"],
  ["speak","spoke","spoken","hablar"],
  ["lose","lost","lost","perder"],
  ["read","read","read","leer"],
  ["grow","grew","grown","crecer"],
  ["win","won","won","ganar"],
  ["teach","taught","taught","enseñar"],
  ["understand","understood","understood","entender"],
  ["eat","ate","eaten","comer"],
  ["drink","drank","drunk","beber"],
  ["drive","drove","driven","conducir"],
  ["buy","bought","bought","comprar"],
  ["sell","sold","sold","vender"],
  ["send","sent","sent","enviar"],
  ["build","built","built","construir"],
  ["sleep","slept","slept","dormir"],
  ["wear","wore","worn","llevar puesto / vestir"],
  ["choose","chose","chosen","elegir"],
  ["break","broke","broken","romper"],
  ["catch","caught","caught","atrapar"],
  ["fall","fell","fallen","caer"],
  ["forget","forgot","forgotten","olvidar"],
  ["fly","flew","flown","volar"]
 */
  // ["be","was/were","been","ser / estar"],
  // ["become","became","become","convertirse / llegar a ser"],
  // ["begin","began","begun","empezar"],
  // ["bend","bent","bent","doblar"],
  // ["bet","bet","bet","apostar"],
  // ["bind","bound","bound","atar"],
  // ["bite","bit","bitten","morder"],
  // ["bleed","bled","bled","sangrar"],
  // ["blow","blew","blown","soplar"],
  // ["break","broke","broken","romper"],
  // ["breed","bred","bred","criar"],
  // ["bring","brought","brought","traer"],
  // ["broadcast","broadcast","broadcast","transmitir"],
  // ["build","built","built","construir"],
  // ["burn","burned","burned","quemar"],
  // ["burst","burst","burst","estallar"],
  // ["buy","bought","bought","comprar"],
  // ["cast","cast","cast","lanzar / arrojar"],
  // ["catch","caught","caught","atrapar"],
  // ["choose","chose","chosen","elegir"],
  // ["cling","clung","clung","aferrarse"],
  // ["come","came","come","venir"],
  // ["cost","cost","cost","costar"],
  // ["creep","crept","crept","arrastrarse"],
  // ["cut","cut","cut","cortar"],
  // ["deal","dealt","dealt","tratar / negociar"],
  // ["dig","dug","dug","cavar"],
  // ["dive","dove","dived","bucear / zambullirse"],
  // ["do","did","done","hacer"],
  // ["draw","drew","drawn","dibujar"],
  // ["dream","dreamed","dreamed","soñar"],
  // ["drink","drank","drunk","beber"],
  // ["drive","drove","driven","conducir"],
  // ["eat","ate","eaten","comer"],
  // ["fall","fell","fallen","caer"],
  // ["feed","fed","fed","alimentar"],
  // ["feel","felt","felt","sentir"],
  // ["fight","fought","fought","pelear"],
  // ["find","found","found","encontrar"],
  // ["fit","fit","fit","encajar / quedar bien"],
  // ["flee","fled","fled","huir"],
  // ["fling","flung","flung","arrojar"],
  // ["fly","flew","flown","volar"],
  // ["forbid","forbade","forbidden","prohibir"],
  // ["forecast","forecast","forecast","pronosticar"],
  // ["forget","forgot","forgotten","olvidar"],
  // ["forgive","forgave","forgiven","perdonar"],
  // ["freeze","froze","frozen","congelar"],
  // ["get","got","gotten","obtener"],
  // ["give","gave","given","dar"],
  // ["go","went","gone","ir"],
  // ["grind","ground","ground","moler"],
  // ["grow","grew","grown","crecer"],
  // ["hang","hung","hung","colgar"],
  // ["have","had","had","tener / haber"],
  // ["hear","heard","heard","oír / escuchar"],
  // ["hide","hid","hidden","esconder"],
  // ["hit","hit","hit","golpear"],
  // ["hold","held","held","sostener"],
  // ["hurt","hurt","hurt","lastimar / doler"],
  // ["keep","kept","kept","mantener / conservar"],
  // ["know","knew","known","saber / conocer"],
  // ["lay","laid","laid","poner / colocar"],
  // ["lead","led","led","liderar / guiar"],
  // ["learn","learned","learned","aprender"],
  // ["leave","left","left","dejar / salir"],
  // ["lend","lent","lent","prestar"],
  // ["let","let","let","dejar / permitir"],
  // ["lie","lay","lain","acostarse / yacer"],
  // ["light","lit","lit","encender / iluminar"],
  // ["lose","lost","lost","perder"],
  // ["make","made","made","hacer / fabricar"],
  // ["mean","meant","meant","significar"],
  // ["meet","met","met","conocer / encontrarse"],
  // ["mistake","mistook","mistaken","equivocarse"],
  // ["overcome","overcame","overcome","superar"],
  // ["overtake","overtook","overtaken","rebasar / adelantar"],
  // ["pay","paid","paid","pagar"],
  // ["prove","proved","proven","probar / demostrar"],
  // ["put","put","put","poner"],
  // ["quit","quit","quit","renunciar / dejar"],
  // ["read","read","read","leer"],
  // ["rid","rid","rid","librar / deshacerse"],
  // ["ride","rode","ridden","montar"],
  // ["ring","rang","rung","sonar / llamar"],
  // ["rise","rose","risen","elevarse / levantarse"],
  // ["run","ran","run","correr"],
  // ["saw","sawed","sawn","serrar"],
  // ["say","said","said","decir"],
  // ["see","saw","seen","ver"],
  // ["seek","sought","sought","buscar"],
  // ["sell","sold","sold","vender"],
  // ["send","sent","sent","enviar"],
  // ["set","set","set","establecer / colocar"],
  // ["sew","sewed","sewn","coser"],
  // ["shake","shook","shaken","sacudir"],
  // ["shave","shaved","shaven","afeitar"],
  // ["shoot","shot","shot","disparar"],
  // ["show","showed","shown","mostrar"],
  // ["shut","shut","shut","cerrar"],
  // ["sing","sang","sung","cantar"],
  // ["sink","sank","sunk","hundir"],
  // ["sit","sat","sat","sentarse"],
  // ["sleep","slept","slept","dormir"],
  // ["slide","slid","slid","deslizar"],
  // ["smell","smelled","smelled","oler"],
  // ["speak","spoke","spoken","hablar"],
  // ["speed","sped","sped","acelerar"],
  // ["spell","spelled","spelled","deletrear"],
  // ["spend","spent","spent","gastar / pasar tiempo"],
  // ["split","split","split","dividir / partir"],
  // ["spoil","spoiled","spoiled","estropear / mimar"],
  // ["spread","spread","spread","extender / esparcir"],
  // ["stand","stood","stood","estar de pie"],
  // ["steal","stole","stolen","robar"],
  // ["stick","stuck","stuck","pegar / clavar"],
  // ["sting","stung","stung","picar"],
  // ["strike","struck","struck","golpear / huelga"],
  // ["string","strung","strung","encordar"],
  // ["swear","swore","sworn","jurar"],
  // ["swim","swam","swum","nadar"],
  // ["swing","swung","swung","balancearse"],
  // ["take","took","taken","tomar / llevar"],
  // ["teach","taught","taught","enseñar"],
  // ["tear","tore","torn","rasgar"],
  // ["tell","told","told","decir / contar"],
  // ["think","thought","thought","pensar"],
  // ["throw","threw","thrown","lanzar"],
  // ["understand","understood","understood","entender"],
  // ["undertake","undertook","undertaken","emprender"],
  // ["upset","upset","upset","molestar / disgustar"],
  // ["wake","woke","woken","despertar"],
  // ["wear","wore","worn","llevar puesto / vestir"],
  // ["weep","wept","wept","llorar"],
  // ["wet","wet","wet","mojar"],
  // ["win","won","won","ganar"],
  // ["wind","wound","wound","enrollar"],
  // ["withdraw","withdrew","withdrawn","retirar"],
  // ["write","wrote","written","escribir"],
  // ["arise","arose","arisen","surgir"],
  // ["awake","awoke","awoken","despertar"],
  // ["babysit","babysat","babysat","cuidar niños"],
  // ["beat","beat","beaten","golpear / vencer"]
].map(([base, past, pp, es], i) => ({
  id: i + 1,
  base,
  past,
  pp,
  es,
  type: "irregular",
}));